var elements = [
	{data: {id: "headache" }},
	{data: {id: "secretary" }},
	{data: {id: "Nations" }},
	{data: {id: "cord" }},
	{data: {id: "elements" }},
	{data: {id: "University" }},
	{data: {id: "health" }},
	{data: {id: "copyright" }},
	{data: {id: "failure" }},
	{data: {id: "personnel" }},
	{data: {id: "network" }},
	{data: {id: "support" }},
	{data: {id: "services" }},
	{data: {id: "channels" }},
	{data: {id: "shop" }},
	{data: {id: "pollution" }},
	{data: {id: "pension" }},
	{data: {id: "divorce" }},
	{data: {id: "operations" }},
	{data: {id: "ideals" }},
	{data: {id: "disruption" }},
	{data: {id: "benefits" }},
	{data: {id: "removal" }},
	{data: {id: "substance" }},
	{data: {id: "California" }},
	{data: {id: "depreciation" }},
	{data: {id: "breakdown" }},
	{data: {id: "allies" }},
	{data: {id: "radiation" }},
	{data: {id: "nitrogen" }},
	{data: {id: "depression" }},
	{data: {id: "aids" }},
	{data: {id: "pressure" }},
	{data: {id: "bodies" }},
	{data: {id: "diabetes" }},
	{data: {id: "effects" }},
	{data: {id: "alcoholism" }},
	{data: {id: "chronic disease" }},
	{data: {id: "system" }},
	{data: {id: "research" }},
	{data: {id: "prenatal" }},
	{data: {id: "accommodation" }},
	{data: {id: "abuse" }},
	{data: {id: "dialysis" }},
	{data: {id: "insurance" }},
	{data: {id: "President" }},
	{data: {id: "security" }},
	{data: {id: "treatment" }},
	{data: {id: "matters" }},
	{data: {id: "housing" }},
	{data: {id: "Britain" }},
	{data: {id: "police" }},
	{data: {id: "Japan" }},
	{data: {id: "systems" }},
	{data: {id: "racism" }},
	{data: {id: "center" }},
	{data: {id: "trust" }},
	{data: {id: "human" }},
	{data: {id: "disabilities" }},
	{data: {id: "names" }},
	{data: {id: "facilities" }},
	{data: {id: "monitoring" }},
	{data: {id: "stroke" }},
	{data: {id: "illness" }},
	{data: {id: "Gulf" }},
	{data: {id: "Hospital" }},
	{data: {id: "distribution" }},
	{data: {id: "asthma" }},
	{data: {id: "obesity" }},
	{data: {id: "studies" }},
	{data: {id: "growth" }},
	{data: {id: "hydrogen" }},
	{data: {id: "infrastructure" }},
	{data: {id: "unemployment" }},
	{data: {id: "fairness" }},
	{data: {id: "Texas" }},
	{data: {id: "documentation" }},
	{data: {id: "Russia" }},
	{data: {id: "International" }},
	{data: {id: "data" }},
	{data: {id: "epilepsy" }},
	{data: {id: "enforcement" }},
	{data: {id: "transportation" }},
	{data: {id: "retirement" }},
	{data: {id: "violence" }},
	{data: {id: "China" }},
	{data: {id: "Congress" }},
	{data: {id: "atrophy" }},
	{data: {id: "centers" }},
	{data: {id: "Argentina" }},
	{data: {id: "Mexico" }},
	{data: {id: "maintenance" }},
	{data: {id: "temperature" }},
	{data: {id: "PC" }},
	{data: {id: "roads" }},
	{data: {id: "Iran" }},
	{data: {id: "therapy" }},
	{data: {id: "Peru" }},
	{data: {id: "constipation" }},
	{data: {id: "dental" }},
	{data: {id: "voice" }},
	{data: {id: "Paris" }},
	{data: {id: "store" }},
	{data: {id: "training" }},
	{data: {id: "procedure" }},
	{data: {id: "carbon" }},
	{data: {id: "ALS" }},
	{data: {id: "sets" }},
	{data: {id: "institutes" }},
	{data: {id: "abnormalities" }},
	{data: {id: "addiction" }},
	{data: {id: "malaria" }},
	{data: {id: "coverage" }},
	{data: {id: "zinc" }},
	{data: {id: "injustice" }},
	{data: {id: "injury" }},
	{data: {id: "care" }},
	{data: {id: "hypertension" }},
	{data: {id: "computer" }},
	{data: {id: "processing" }},
	{data: {id: "damage" }},
	{data: {id: "helium" }},
	{data: {id: "problems" }},
	{data: {id: "lung" }},
	{data: {id: "Canada" }},
	{data: {id: "emerging markets" }},
	{data: {id: "age" }},
	{data: {id: "television" }},
	{data: {id: "calcium" }},
	{data: {id: "AIDS" }},
	{data: {id: "communications" }},
	{data: {id: "Chicago" }},
	{data: {id: "marriage" }},
	{data: {id: "aircraft" }},
	{data: {id: "numbers" }},
	{data: {id: "freedom" }},
	{data: {id: "commitment" }},
	{data: {id: "India" }},
	{data: {id: "overhead" }},
	{data: {id: "sclerosis" }},
	{data: {id: "technology" }},
	{data: {id: "exchange" }},
	{data: {id: "child" }},
	{data: {id: "democracy" }},
	{data: {id: "water" }},
	{data: {id: "home" }},
	{data: {id: "advice" }},
	{data: {id: "planning" }},
	{data: {id: "Social" }},
	{data: {id: "consultation" }},
	{data: {id: "privacy" }},
	{data: {id: "organs" }},
	{data: {id: "schizophrenia" }},
	{data: {id: "repair" }},
	{data: {id: "guidance" }},
	{data: {id: "change" }},
	{data: {id: "placement" }},
	{data: {id: "shortness" }},
	{data: {id: "response" }},
	{data: {id: "Center" }},
	{data: {id: "Brazil" }},
	{data: {id: "e-mail" }},
	{data: {id: "positions" }},
	{data: {id: "difficulties" }},
	{data: {id: "tubes" }},
	{data: {id: "finance" }},
	{data: {id: "cancer" }},
	{data: {id: "climate" }},
	{data: {id: "gain" }},
	{data: {id: "interest" }},
	{data: {id: "Association" }},
	{data: {id: "cost" }},
	{data: {id: "iron" }},
	{data: {id: "erosion" }},
	{data: {id: "spreadsheet" }},
	{data: {id: "mediation" }},
	{data: {id: "marketing" }},
	{data: {id: "autism" }},
	{data: {id: "Cuba" }},
	{data: {id: "banking" }},
	{data: {id: "disease" }},
	{data: {id: "anxiety" }},
	{data: {id: "Internet" }},
	{data: {id: "selection" }},
	{data: {id: "rates" }},
	{data: {id: "Asia" }},
	{data: {id: "delinquency" }},
	{data: {id: "library" }},
	{data: {id: "customer" }},
	{data: {id: "management" }},
	{data: {id: "software" }},
	{data: {id: "pool" }},
	{data: {id: "Vietnam" }},
	{data: {id: "environment" }},
	{data: {id: "spinal" }},
	{data: {id: "means" }},
	{data: {id: "categories" }},
	{data: {id: "crime" }},
	{data: {id: "stations" }},
	{data: {id: "Fund" }},
	{data: {id: "pain" }},
	{data: {id: "life" }},
	{data: {id: "powers" }},
	{data: {id: "details" }},
	{data: {id: "use" }},
	{data: {id: "kidney" }},
	{data: {id: "retardation" }},
	{data: {id: "liver" }},
	{data: {id: "telephone" }},
	{data: {id: "disorders" }},
	{data: {id: "aluminum" }},
	{data: {id: "funds" }},
	{data: {id: "values" }},
	{data: {id: "storage" }},
	{data: {id: "control" }},
	{data: {id: "nausea" }},
	{data: {id: "air" }},
	{data: {id: "equipment" }},
	{data: {id: "emergency" }},
	{data: {id: "development" }},
	{data: {id: "oxygen" }},
	{data: {id: "GDP" }},
	{data: {id: "attack" }},
	{data: {id: "diarrhea" }},
	{data: {id: "nations" }},
	{data: {id: "France" }},
	{data: {id: "United" }},
	{data: {id: "projects" }},
	{data: {id: "rights" }},
	{data: {id: "loss" }},
	{data: {id: "palsy" }},
	{data: {id: "Organization" }},
	{data: {id: "multiple" }},
	{data: {id: "Union" }},
	{data: {id: "physician" }},
	{data: {id: "heart" }},
	{data: {id: "Kingdom" }},
	{data: {id: "assistance" }},
	{data: {id: "alcohol" }},
	{data: {id: "Committee" }},
	{data: {id: "protection" }},
	{data: {id: "translation" }},
	{data: {id: "Institute" }},
	{data: {id: "family" }},
	{data: {id: "lungs" }},
	{data: {id: "light" }},
	{data: {id: "productivity" }},
	{data: {id: "drug" }},
	{data: {id: "Africa" }},
	{data: {id: "laboratory" }},
	{data: {id: "Bank" }},
	{data: {id: "speech" }},
	{data: {id: "needs" }},
	{data: {id: "England" }},
	{data: {id: "performance" }},
	{data: {id: "fear" }},
	{data: {id: "Security" }},
	{data: {id: "poverty" }},
	{data: {id: "mental" }},
	{data: {id: "places" }},
	{data: {id: "World" }},
	{data: {id: "surgery" }},
	{data: {id: "pregnancy" }},
	{data: {id: "dementia" }},
	{data: {id: "States" }},
	{data: {id: "syndrome" }},
	{data: {id: "Council" }},
	{data: {id: "devices" }},
	{data: {id: "breath" }},
	{data: {id: "station" }},
	{data: {id: "welfare" }},
	{data: {id: "shipping" }},
	{data: {id: "access" }},
	{data: {id: "honesty" }},
	{data: {id: "memory" }},
	{data: {id: "Windows" }},
	{data: {id: "costs" }},
	{data: {id: "blood" }},

	{data: {id: "systems_aircraft", source: "systems", target: "aircraft"}},
	{data: {id: "positions_secretary", source: "positions", target: "secretary"}},
	{data: {id: "services_mediation", source: "services", target: "mediation"}},
	{data: {id: "matters_welfare", source: "matters", target: "welfare"}},
	{data: {id: "elements_security", source: "elements", target: "security"}},
	{data: {id: "problems_system", source: "problems", target: "system"}},
	{data: {id: "services_marketing", source: "services", target: "marketing"}},
	{data: {id: "effects_gain", source: "effects", target: "gain"}},
	{data: {id: "effects_diarrhea", source: "effects", target: "diarrhea"}},
	{data: {id: "facilities_pool", source: "facilities", target: "pool"}},
	{data: {id: "services_health", source: "services", target: "health"}},
	{data: {id: "facilities_shop", source: "facilities", target: "shop"}},
	{data: {id: "problems_unemployment", source: "problems", target: "unemployment"}},
	{data: {id: "data_names", source: "data", target: "names"}},
	{data: {id: "technology_computer", source: "technology", target: "computer"}},
	{data: {id: "devices_memory", source: "devices", target: "memory"}},
	{data: {id: "values_fairness", source: "values", target: "fairness"}},
	{data: {id: "emerging markets_India", source: "emerging markets", target: "India"}},
	{data: {id: "nations_United", source: "nations", target: "United"}},
	{data: {id: "problems_drug", source: "problems", target: "drug"}},
	{data: {id: "services_removal", source: "services", target: "removal"}},
	{data: {id: "elements_aluminum", source: "elements", target: "aluminum"}},
	{data: {id: "places_stations", source: "places", target: "stations"}},
	{data: {id: "services_shipping", source: "services", target: "shipping"}},
	{data: {id: "bodies_World", source: "bodies", target: "World"}},
	{data: {id: "nations_Vietnam", source: "nations", target: "Vietnam"}},
	{data: {id: "matters_selection", source: "matters", target: "selection"}},
	{data: {id: "values_health", source: "values", target: "health"}},
	{data: {id: "elements_cost", source: "elements", target: "cost"}},
	{data: {id: "effects_disruption", source: "effects", target: "disruption"}},
	{data: {id: "infrastructure_network", source: "infrastructure", target: "network"}},
	{data: {id: "services_consultation", source: "services", target: "consultation"}},
	{data: {id: "details_numbers", source: "details", target: "numbers"}},
	{data: {id: "infrastructure_transportation", source: "infrastructure", target: "transportation"}},
	{data: {id: "problems_pressure", source: "problems", target: "pressure"}},
	{data: {id: "places_Mexico", source: "places", target: "Mexico"}},
	{data: {id: "problems_environment", source: "problems", target: "environment"}},
	{data: {id: "institutes_Institute", source: "institutes", target: "Institute"}},
	{data: {id: "disorders_cord", source: "disorders", target: "cord"}},
	{data: {id: "bodies_International", source: "bodies", target: "International"}},
	{data: {id: "details_age", source: "details", target: "age"}},
	{data: {id: "places_Texas", source: "places", target: "Texas"}},
	{data: {id: "services_Internet", source: "services", target: "Internet"}},
	{data: {id: "elements_helium", source: "elements", target: "helium"}},
	{data: {id: "problems_pollution", source: "problems", target: "pollution"}},
	{data: {id: "organs_lungs", source: "organs", target: "lungs"}},
	{data: {id: "problems_anxiety", source: "problems", target: "anxiety"}},
	{data: {id: "organs_liver", source: "organs", target: "liver"}},
	{data: {id: "services_personnel", source: "services", target: "personnel"}},
	{data: {id: "services_care", source: "services", target: "care"}},
	{data: {id: "problems_delinquency", source: "problems", target: "delinquency"}},
	{data: {id: "software_Windows", source: "software", target: "Windows"}},
	{data: {id: "services_response", source: "services", target: "response"}},
	{data: {id: "services_facilities", source: "services", target: "facilities"}},
	{data: {id: "facilities_library", source: "facilities", target: "library"}},
	{data: {id: "services_support", source: "services", target: "support"}},
	{data: {id: "matters_advice", source: "matters", target: "advice"}},
	{data: {id: "elements_hydrogen", source: "elements", target: "hydrogen"}},
	{data: {id: "needs_costs", source: "needs", target: "costs"}},
	{data: {id: "facilities_centers", source: "facilities", target: "centers"}},
	{data: {id: "ideals_human", source: "ideals", target: "human"}},
	{data: {id: "devices_PC", source: "devices", target: "PC"}},
	{data: {id: "problems_commitment", source: "problems", target: "commitment"}},
	{data: {id: "problems_blood", source: "problems", target: "blood"}},
	{data: {id: "services_customer", source: "services", target: "customer"}},
	{data: {id: "nations_China", source: "nations", target: "China"}},
	{data: {id: "problems_rates", source: "problems", target: "rates"}},
	{data: {id: "services_software", source: "services", target: "software"}},
	{data: {id: "costs_services", source: "costs", target: "services"}},
	{data: {id: "problems_breath", source: "problems", target: "breath"}},
	{data: {id: "bodies_Nations", source: "bodies", target: "Nations"}},
	{data: {id: "bodies_Committee", source: "bodies", target: "Committee"}},
	{data: {id: "software_spreadsheet", source: "software", target: "spreadsheet"}},
	{data: {id: "positions_President", source: "positions", target: "President"}},
	{data: {id: "problems_alcoholism", source: "problems", target: "alcoholism"}},
	{data: {id: "elements_nitrogen", source: "elements", target: "nitrogen"}},
	{data: {id: "matters_privacy", source: "matters", target: "privacy"}},
	{data: {id: "benefits_services", source: "benefits", target: "services"}},
	{data: {id: "places_University", source: "places", target: "University"}},
	{data: {id: "effects_constipation", source: "effects", target: "constipation"}},
	{data: {id: "nations_India", source: "nations", target: "India"}},
	{data: {id: "disabilities_palsy", source: "disabilities", target: "palsy"}},
	{data: {id: "nations_States", source: "nations", target: "States"}},
	{data: {id: "equipment_systems", source: "equipment", target: "systems"}},
	{data: {id: "problems_pregnancy", source: "problems", target: "pregnancy"}},
	{data: {id: "problems_rights", source: "problems", target: "rights"}},
	{data: {id: "matters_costs", source: "matters", target: "costs"}},
	{data: {id: "services_planning", source: "services", target: "planning"}},
	{data: {id: "matters_enforcement", source: "matters", target: "enforcement"}},
	{data: {id: "data_use", source: "data", target: "use"}},
	{data: {id: "bodies_Union", source: "bodies", target: "Union"}},
	{data: {id: "needs_maintenance", source: "needs", target: "maintenance"}},
	{data: {id: "effects_radiation", source: "effects", target: "radiation"}},
	{data: {id: "services_exchange", source: "services", target: "exchange"}},
	{data: {id: "services_distribution", source: "services", target: "distribution"}},
	{data: {id: "services_banking", source: "services", target: "banking"}},
	{data: {id: "services_family", source: "services", target: "family"}},
	{data: {id: "bodies_Bank", source: "bodies", target: "Bank"}},
	{data: {id: "services_dialysis", source: "services", target: "dialysis"}},
	{data: {id: "facilities_Hospital", source: "facilities", target: "Hospital"}},
	{data: {id: "problems_crime", source: "problems", target: "crime"}},
	{data: {id: "effects_headache", source: "effects", target: "headache"}},
	{data: {id: "nations_Kingdom", source: "nations", target: "Kingdom"}},
	{data: {id: "disorders_atrophy", source: "disorders", target: "atrophy"}},
	{data: {id: "problems_housing", source: "problems", target: "housing"}},
	{data: {id: "nations_France", source: "nations", target: "France"}},
	{data: {id: "infrastructure_communications", source: "infrastructure", target: "communications"}},
	{data: {id: "services_management", source: "services", target: "management"}},
	{data: {id: "places_Japan", source: "places", target: "Japan"}},
	{data: {id: "problems_change", source: "problems", target: "change"}},
	{data: {id: "projects_studies", source: "projects", target: "studies"}},
	{data: {id: "services_child", source: "services", target: "child"}},
	{data: {id: "problems_breakdown", source: "problems", target: "breakdown"}},
	{data: {id: "services_placement", source: "services", target: "placement"}},
	{data: {id: "means_telephone", source: "means", target: "telephone"}},
	{data: {id: "nations_Union", source: "nations", target: "Union"}},
	{data: {id: "matters_finance", source: "matters", target: "finance"}},
	{data: {id: "benefits_protection", source: "benefits", target: "protection"}},
	{data: {id: "documentation_data", source: "documentation", target: "data"}},
	{data: {id: "places_California", source: "places", target: "California"}},
	{data: {id: "means_television", source: "means", target: "television"}},
	{data: {id: "disorders_stroke", source: "disorders", target: "stroke"}},
	{data: {id: "problems_depression", source: "problems", target: "depression"}},
	{data: {id: "data_GDP", source: "data", target: "GDP"}},
	{data: {id: "places_Gulf", source: "places", target: "Gulf"}},
	{data: {id: "problems_shortness", source: "problems", target: "shortness"}},
	{data: {id: "benefits_retirement", source: "benefits", target: "retirement"}},
	{data: {id: "services_monitoring", source: "services", target: "monitoring"}},
	{data: {id: "nations_England", source: "nations", target: "England"}},
	{data: {id: "places_Paris", source: "places", target: "Paris"}},
	{data: {id: "facilities_laboratory", source: "facilities", target: "laboratory"}},
	{data: {id: "powers_Iran", source: "powers", target: "Iran"}},
	{data: {id: "matters_protection", source: "matters", target: "protection"}},
	{data: {id: "difficulties_problems", source: "difficulties", target: "problems"}},
	{data: {id: "disorders_pain", source: "disorders", target: "pain"}},
	{data: {id: "problems_cancer", source: "problems", target: "cancer"}},
	{data: {id: "values_freedom", source: "values", target: "freedom"}},
	{data: {id: "disorders_syndrome", source: "disorders", target: "syndrome"}},
	{data: {id: "values_honesty", source: "values", target: "honesty"}},
	{data: {id: "nations_Peru", source: "nations", target: "Peru"}},
	{data: {id: "problems_illness", source: "problems", target: "illness"}},
	{data: {id: "nations_Iran", source: "nations", target: "Iran"}},
	{data: {id: "facilities_store", source: "facilities", target: "store"}},
	{data: {id: "services_access", source: "services", target: "access"}},
	{data: {id: "matters_rights", source: "matters", target: "rights"}},
	{data: {id: "problems_injustice", source: "problems", target: "injustice"}},
	{data: {id: "problems_racism", source: "problems", target: "racism"}},
	{data: {id: "effects_problems", source: "effects", target: "problems"}},
	{data: {id: "services_voice", source: "services", target: "voice"}},
	{data: {id: "problems_disorders", source: "problems", target: "disorders"}},
	{data: {id: "bodies_Congress", source: "bodies", target: "Congress"}},
	{data: {id: "costs_depreciation", source: "costs", target: "depreciation"}},
	{data: {id: "problems_malaria", source: "problems", target: "malaria"}},
	{data: {id: "problems_climate", source: "problems", target: "climate"}},
	{data: {id: "benefits_Social", source: "benefits", target: "Social"}},
	{data: {id: "places_Chicago", source: "places", target: "Chicago"}},
	{data: {id: "elements_iron", source: "elements", target: "iron"}},
	{data: {id: "bodies_United", source: "bodies", target: "United"}},
	{data: {id: "rights_speech", source: "rights", target: "speech"}},
	{data: {id: "problems_failure", source: "problems", target: "failure"}},
	{data: {id: "problems_control", source: "problems", target: "control"}},
	{data: {id: "services_translation", source: "services", target: "translation"}},
	{data: {id: "devices_tubes", source: "devices", target: "tubes"}},
	{data: {id: "nations_Argentina", source: "nations", target: "Argentina"}},
	{data: {id: "facilities_center", source: "facilities", target: "center"}},
	{data: {id: "services_trust", source: "services", target: "trust"}},
	{data: {id: "problems_nausea", source: "problems", target: "nausea"}},
	{data: {id: "systems_security", source: "systems", target: "security"}},
	{data: {id: "services_physician", source: "services", target: "physician"}},
	{data: {id: "problems_performance", source: "problems", target: "performance"}},
	{data: {id: "benefits_pension", source: "benefits", target: "pension"}},
	{data: {id: "costs_interest", source: "costs", target: "interest"}},
	{data: {id: "values_democracy", source: "values", target: "democracy"}},
	{data: {id: "services_storage", source: "services", target: "storage"}},
	{data: {id: "services_data", source: "services", target: "data"}},
	{data: {id: "services_police", source: "services", target: "police"}},
	{data: {id: "places_China", source: "places", target: "China"}},
	{data: {id: "benefits_life", source: "benefits", target: "life"}},
	{data: {id: "disorders_hypertension", source: "disorders", target: "hypertension"}},
	{data: {id: "services_housing", source: "services", target: "housing"}},
	{data: {id: "nations_Brazil", source: "nations", target: "Brazil"}},
	{data: {id: "disorders_schizophrenia", source: "disorders", target: "schizophrenia"}},
	{data: {id: "projects_University", source: "projects", target: "University"}},
	{data: {id: "services_treatment", source: "services", target: "treatment"}},
	{data: {id: "services_processing", source: "services", target: "processing"}},
	{data: {id: "disorders_obesity", source: "disorders", target: "obesity"}},
	{data: {id: "services_telephone", source: "services", target: "telephone"}},
	{data: {id: "matters_age", source: "matters", target: "age"}},
	{data: {id: "elements_crime", source: "elements", target: "crime"}},
	{data: {id: "services_training", source: "services", target: "training"}},
	{data: {id: "benefits_dental", source: "benefits", target: "dental"}},
	{data: {id: "costs_overhead", source: "costs", target: "overhead"}},
	{data: {id: "facilities_station", source: "facilities", target: "station"}},
	{data: {id: "means_communications", source: "means", target: "communications"}},
	{data: {id: "elements_carbon", source: "elements", target: "carbon"}},
	{data: {id: "research_studies", source: "research", target: "studies"}},
	{data: {id: "matters_projects", source: "matters", target: "projects"}},
	{data: {id: "problems_substance", source: "problems", target: "substance"}},
	{data: {id: "nations_Japan", source: "nations", target: "Japan"}},
	{data: {id: "nations_Cuba", source: "nations", target: "Cuba"}},
	{data: {id: "problems_fear", source: "problems", target: "fear"}},
	{data: {id: "services_control", source: "services", target: "control"}},
	{data: {id: "facilities_stations", source: "facilities", target: "stations"}},
	{data: {id: "disorders_spinal", source: "disorders", target: "spinal"}},
	{data: {id: "elements_calcium", source: "elements", target: "calcium"}},
	{data: {id: "places_centers", source: "places", target: "centers"}},
	{data: {id: "rights_freedom", source: "rights", target: "freedom"}},
	{data: {id: "ideals_rights", source: "ideals", target: "rights"}},
	{data: {id: "chronic disease_disease", source: "chronic disease", target: "disease"}},
	{data: {id: "disorders_multiple", source: "disorders", target: "multiple"}},
	{data: {id: "problems_AIDS", source: "problems", target: "AIDS"}},
	{data: {id: "elements_light", source: "elements", target: "light"}},
	{data: {id: "bodies_services", source: "bodies", target: "services"}},
	{data: {id: "matters_marriage", source: "matters", target: "marriage"}},
	{data: {id: "problems_poverty", source: "problems", target: "poverty"}},
	{data: {id: "funds_Fund", source: "funds", target: "Fund"}},
	{data: {id: "disabilities_autism", source: "disabilities", target: "autism"}},
	{data: {id: "disorders_injury", source: "disorders", target: "injury"}},
	{data: {id: "organs_heart", source: "organs", target: "heart"}},
	{data: {id: "disease_diabetes", source: "disease", target: "diabetes"}},
	{data: {id: "problems_air", source: "problems", target: "air"}},
	{data: {id: "services_funds", source: "services", target: "funds"}},
	{data: {id: "channels_television", source: "channels", target: "television"}},
	{data: {id: "services_accommodation", source: "services", target: "accommodation"}},
	{data: {id: "services_surgery", source: "services", target: "surgery"}},
	{data: {id: "organs_kidney", source: "organs", target: "kidney"}},
	{data: {id: "emerging markets_China", source: "emerging markets", target: "China"}},
	{data: {id: "organs_lung", source: "organs", target: "lung"}},
	{data: {id: "services_insurance", source: "services", target: "insurance"}},
	{data: {id: "bodies_Association", source: "bodies", target: "Association"}},
	{data: {id: "centers_Center", source: "centers", target: "Center"}},
	{data: {id: "problems_abuse", source: "problems", target: "abuse"}},
	{data: {id: "services_prenatal", source: "services", target: "prenatal"}},
	{data: {id: "benefits_Security", source: "benefits", target: "Security"}},
	{data: {id: "disease_asthma", source: "disease", target: "asthma"}},
	{data: {id: "devices_systems", source: "devices", target: "systems"}},
	{data: {id: "problems_erosion", source: "problems", target: "erosion"}},
	{data: {id: "disease_heart", source: "disease", target: "heart"}},
	{data: {id: "technology_systems", source: "technology", target: "systems"}},
	{data: {id: "positions_management", source: "positions", target: "management"}},
	{data: {id: "matters_copyright", source: "matters", target: "copyright"}},
	{data: {id: "services_therapy", source: "services", target: "therapy"}},
	{data: {id: "problems_growth", source: "problems", target: "growth"}},
	{data: {id: "nations_Mexico", source: "nations", target: "Mexico"}},
	{data: {id: "services_emergency", source: "services", target: "emergency"}},
	{data: {id: "nations_Canada", source: "nations", target: "Canada"}},
	{data: {id: "categories_services", source: "categories", target: "services"}},
	{data: {id: "institutes_Center", source: "institutes", target: "Center"}},
	{data: {id: "operations_management", source: "operations", target: "management"}},
	{data: {id: "problems_damage", source: "problems", target: "damage"}},
	{data: {id: "data_temperature", source: "data", target: "temperature"}},
	{data: {id: "abnormalities_disease", source: "abnormalities", target: "disease"}},
	{data: {id: "disorders_autism", source: "disorders", target: "autism"}},
	{data: {id: "problems_loss", source: "problems", target: "loss"}},
	{data: {id: "disorders_ALS", source: "disorders", target: "ALS"}},
	{data: {id: "infrastructure_roads", source: "infrastructure", target: "roads"}},
	{data: {id: "projects_facilities", source: "projects", target: "facilities"}},
	{data: {id: "costs_cost", source: "costs", target: "cost"}},
	{data: {id: "problems_attack", source: "problems", target: "attack"}},
	{data: {id: "disabilities_retardation", source: "disabilities", target: "retardation"}},
	{data: {id: "places_Africa", source: "places", target: "Africa"}},
	{data: {id: "services_guidance", source: "services", target: "guidance"}},
	{data: {id: "devices_sets", source: "devices", target: "sets"}},
	{data: {id: "devices_aids", source: "devices", target: "aids"}},
	{data: {id: "services_e-mail", source: "services", target: "e-mail"}},
	{data: {id: "disabilities_mental", source: "disabilities", target: "mental"}},
	{data: {id: "benefits_productivity", source: "benefits", target: "productivity"}},
	{data: {id: "disorders_addiction", source: "disorders", target: "addiction"}},
	{data: {id: "services_repair", source: "services", target: "repair"}},
	{data: {id: "problems_alcohol", source: "problems", target: "alcohol"}},
	{data: {id: "elements_oxygen", source: "elements", target: "oxygen"}},
	{data: {id: "benefits_coverage", source: "benefits", target: "coverage"}},
	{data: {id: "services_assistance", source: "services", target: "assistance"}},
	{data: {id: "disorders_dementia", source: "disorders", target: "dementia"}},
	{data: {id: "places_Asia", source: "places", target: "Asia"}},
	{data: {id: "bodies_Organization", source: "bodies", target: "Organization"}},
	{data: {id: "channels_Internet", source: "channels", target: "Internet"}},
	{data: {id: "services_transportation", source: "services", target: "transportation"}},
	{data: {id: "matters_procedure", source: "matters", target: "procedure"}},
	{data: {id: "problems_development", source: "problems", target: "development"}},
	{data: {id: "problems_violence", source: "problems", target: "violence"}},
	{data: {id: "services_home", source: "services", target: "home"}},
	{data: {id: "nations_Britain", source: "nations", target: "Britain"}},
	{data: {id: "disorders_epilepsy", source: "disorders", target: "epilepsy"}},
	{data: {id: "infrastructure_housing", source: "infrastructure", target: "housing"}},
	{data: {id: "infrastructure_facilities", source: "infrastructure", target: "facilities"}},
	{data: {id: "problems_water", source: "problems", target: "water"}},
	{data: {id: "disorders_disease", source: "disorders", target: "disease"}},
	{data: {id: "disorders_sclerosis", source: "disorders", target: "sclerosis"}},
	{data: {id: "places_Canada", source: "places", target: "Canada"}},
	{data: {id: "places_Russia", source: "places", target: "Russia"}},
	{data: {id: "infrastructure_systems", source: "infrastructure", target: "systems"}},
	{data: {id: "allies_Japan", source: "allies", target: "Japan"}},
	{data: {id: "services_development", source: "services", target: "development"}},
	{data: {id: "matters_divorce", source: "matters", target: "divorce"}},
	{data: {id: "bodies_Council", source: "bodies", target: "Council"}},
	{data: {id: "places_India", source: "places", target: "India"}},
	{data: {id: "elements_zinc", source: "elements", target: "zinc"}},
	{data: {id: "data_rates", source: "data", target: "rates"}}
];
