var elements = [
	{data: {id: "elements"}},
	{data: {id: "security"}},
	{data: {id: "elements_security", source: "elements", target: "security"}},
	{data: {id: "aluminum"}},
	{data: {id: "elements_aluminum", source: "elements", target: "aluminum"}},
	{data: {id: "cost"}},
	{data: {id: "elements_cost", source: "elements", target: "cost"}},
	{data: {id: "helium"}},
	{data: {id: "elements_helium", source: "elements", target: "helium"}},
	{data: {id: "hydrogen"}},
	{data: {id: "elements_hydrogen", source: "elements", target: "hydrogen"}},
	{data: {id: "nitrogen"}},
	{data: {id: "elements_nitrogen", source: "elements", target: "nitrogen"}},
	{data: {id: "iron"}},
	{data: {id: "elements_iron", source: "elements", target: "iron"}},
	{data: {id: "crime"}},
	{data: {id: "elements_crime", source: "elements", target: "crime"}},
	{data: {id: "carbon"}},
	{data: {id: "elements_carbon", source: "elements", target: "carbon"}},
	{data: {id: "calcium"}},
	{data: {id: "elements_calcium", source: "elements", target: "calcium"}},
	{data: {id: "light"}},
	{data: {id: "elements_light", source: "elements", target: "light"}},
	{data: {id: "oxygen"}},
	{data: {id: "elements_oxygen", source: "elements", target: "oxygen"}},
	{data: {id: "zinc"}},
	{data: {id: "elements_zinc", source: "elements", target: "zinc"}},
	{data: {id: "channels"}},
	{data: {id: "television"}},
	{data: {id: "channels_television", source: "channels", target: "television"}},
	{data: {id: "Internet"}},
	{data: {id: "channels_Internet", source: "channels", target: "Internet"}},
	{data: {id: "operations"}},
	{data: {id: "management"}},
	{data: {id: "operations_management", source: "operations", target: "management"}},
	{data: {id: "ideals"}},
	{data: {id: "human"}},
	{data: {id: "ideals_human", source: "ideals", target: "human"}},
	{data: {id: "rights"}},
	{data: {id: "speech"}},
	{data: {id: "rights_speech", source: "rights", target: "speech"}},
	{data: {id: "freedom"}},
	{data: {id: "rights_freedom", source: "rights", target: "freedom"}},
	{data: {id: "ideals_rights", source: "ideals", target: "rights"}},
	{data: {id: "benefits"}},
	{data: {id: "services"}},
	{data: {id: "mediation"}},
	{data: {id: "services_mediation", source: "services", target: "mediation"}},
	{data: {id: "marketing"}},
	{data: {id: "services_marketing", source: "services", target: "marketing"}},
	{data: {id: "health"}},
	{data: {id: "services_health", source: "services", target: "health"}},
	{data: {id: "removal"}},
	{data: {id: "services_removal", source: "services", target: "removal"}},
	{data: {id: "shipping"}},
	{data: {id: "services_shipping", source: "services", target: "shipping"}},
	{data: {id: "consultation"}},
	{data: {id: "services_consultation", source: "services", target: "consultation"}},
	{data: {id: "Internet"}},
	{data: {id: "services_Internet", source: "services", target: "Internet"}},
	{data: {id: "personnel"}},
	{data: {id: "services_personnel", source: "services", target: "personnel"}},
	{data: {id: "care"}},
	{data: {id: "services_care", source: "services", target: "care"}},
	{data: {id: "response"}},
	{data: {id: "services_response", source: "services", target: "response"}},
	{data: {id: "facilities"}},
	{data: {id: "pool"}},
	{data: {id: "facilities_pool", source: "facilities", target: "pool"}},
	{data: {id: "shop"}},
	{data: {id: "facilities_shop", source: "facilities", target: "shop"}},
	{data: {id: "library"}},
	{data: {id: "facilities_library", source: "facilities", target: "library"}},
	{data: {id: "centers"}},
	{data: {id: "Center"}},
	{data: {id: "centers_Center", source: "centers", target: "Center"}},
	{data: {id: "facilities_centers", source: "facilities", target: "centers"}},
	{data: {id: "Hospital"}},
	{data: {id: "facilities_Hospital", source: "facilities", target: "Hospital"}},
	{data: {id: "laboratory"}},
	{data: {id: "facilities_laboratory", source: "facilities", target: "laboratory"}},
	{data: {id: "store"}},
	{data: {id: "facilities_store", source: "facilities", target: "store"}},
	{data: {id: "center"}},
	{data: {id: "facilities_center", source: "facilities", target: "center"}},
	{data: {id: "station"}},
	{data: {id: "facilities_station", source: "facilities", target: "station"}},
	{data: {id: "stations"}},
	{data: {id: "facilities_stations", source: "facilities", target: "stations"}},
	{data: {id: "services_facilities", source: "services", target: "facilities"}},
	{data: {id: "support"}},
	{data: {id: "services_support", source: "services", target: "support"}},
	{data: {id: "customer"}},
	{data: {id: "services_customer", source: "services", target: "customer"}},
	{data: {id: "software"}},
	{data: {id: "Windows"}},
	{data: {id: "software_Windows", source: "software", target: "Windows"}},
	{data: {id: "spreadsheet"}},
	{data: {id: "software_spreadsheet", source: "software", target: "spreadsheet"}},
	{data: {id: "services_software", source: "services", target: "software"}},
	{data: {id: "planning"}},
	{data: {id: "services_planning", source: "services", target: "planning"}},
	{data: {id: "exchange"}},
	{data: {id: "services_exchange", source: "services", target: "exchange"}},
	{data: {id: "distribution"}},
	{data: {id: "services_distribution", source: "services", target: "distribution"}},
	{data: {id: "banking"}},
	{data: {id: "services_banking", source: "services", target: "banking"}},
	{data: {id: "family"}},
	{data: {id: "services_family", source: "services", target: "family"}},
	{data: {id: "dialysis"}},
	{data: {id: "services_dialysis", source: "services", target: "dialysis"}},
	{data: {id: "management"}},
	{data: {id: "services_management", source: "services", target: "management"}},
	{data: {id: "child"}},
	{data: {id: "services_child", source: "services", target: "child"}},
	{data: {id: "placement"}},
	{data: {id: "services_placement", source: "services", target: "placement"}},
	{data: {id: "monitoring"}},
	{data: {id: "services_monitoring", source: "services", target: "monitoring"}},
	{data: {id: "access"}},
	{data: {id: "services_access", source: "services", target: "access"}},
	{data: {id: "voice"}},
	{data: {id: "services_voice", source: "services", target: "voice"}},
	{data: {id: "translation"}},
	{data: {id: "services_translation", source: "services", target: "translation"}},
	{data: {id: "trust"}},
	{data: {id: "services_trust", source: "services", target: "trust"}},
	{data: {id: "physician"}},
	{data: {id: "services_physician", source: "services", target: "physician"}},
	{data: {id: "storage"}},
	{data: {id: "services_storage", source: "services", target: "storage"}},
	{data: {id: "data"}},
	{data: {id: "names"}},
	{data: {id: "data_names", source: "data", target: "names"}},
	{data: {id: "use"}},
	{data: {id: "data_use", source: "data", target: "use"}},
	{data: {id: "GDP"}},
	{data: {id: "data_GDP", source: "data", target: "GDP"}},
	{data: {id: "temperature"}},
	{data: {id: "data_temperature", source: "data", target: "temperature"}},
	{data: {id: "rates"}},
	{data: {id: "data_rates", source: "data", target: "rates"}},
	{data: {id: "services_data", source: "services", target: "data"}},
	{data: {id: "police"}},
	{data: {id: "services_police", source: "services", target: "police"}},
	{data: {id: "housing"}},
	{data: {id: "services_housing", source: "services", target: "housing"}},
	{data: {id: "treatment"}},
	{data: {id: "services_treatment", source: "services", target: "treatment"}},
	{data: {id: "processing"}},
	{data: {id: "services_processing", source: "services", target: "processing"}},
	{data: {id: "telephone"}},
	{data: {id: "services_telephone", source: "services", target: "telephone"}},
	{data: {id: "training"}},
	{data: {id: "services_training", source: "services", target: "training"}},
	{data: {id: "control"}},
	{data: {id: "services_control", source: "services", target: "control"}},
	{data: {id: "funds"}},
	{data: {id: "Fund"}},
	{data: {id: "funds_Fund", source: "funds", target: "Fund"}},
	{data: {id: "services_funds", source: "services", target: "funds"}},
	{data: {id: "accommodation"}},
	{data: {id: "services_accommodation", source: "services", target: "accommodation"}},
	{data: {id: "surgery"}},
	{data: {id: "services_surgery", source: "services", target: "surgery"}},
	{data: {id: "insurance"}},
	{data: {id: "services_insurance", source: "services", target: "insurance"}},
	{data: {id: "prenatal"}},
	{data: {id: "services_prenatal", source: "services", target: "prenatal"}},
	{data: {id: "therapy"}},
	{data: {id: "services_therapy", source: "services", target: "therapy"}},
	{data: {id: "emergency"}},
	{data: {id: "services_emergency", source: "services", target: "emergency"}},
	{data: {id: "guidance"}},
	{data: {id: "services_guidance", source: "services", target: "guidance"}},
	{data: {id: "e-mail"}},
	{data: {id: "services_e-mail", source: "services", target: "e-mail"}},
	{data: {id: "repair"}},
	{data: {id: "services_repair", source: "services", target: "repair"}},
	{data: {id: "assistance"}},
	{data: {id: "services_assistance", source: "services", target: "assistance"}},
	{data: {id: "transportation"}},
	{data: {id: "services_transportation", source: "services", target: "transportation"}},
	{data: {id: "home"}},
	{data: {id: "services_home", source: "services", target: "home"}},
	{data: {id: "development"}},
	{data: {id: "services_development", source: "services", target: "development"}},
	{data: {id: "benefits_services", source: "benefits", target: "services"}},
	{data: {id: "protection"}},
	{data: {id: "benefits_protection", source: "benefits", target: "protection"}},
	{data: {id: "retirement"}},
	{data: {id: "benefits_retirement", source: "benefits", target: "retirement"}},
	{data: {id: "Social"}},
	{data: {id: "benefits_Social", source: "benefits", target: "Social"}},
	{data: {id: "pension"}},
	{data: {id: "benefits_pension", source: "benefits", target: "pension"}},
	{data: {id: "life"}},
	{data: {id: "benefits_life", source: "benefits", target: "life"}},
	{data: {id: "dental"}},
	{data: {id: "benefits_dental", source: "benefits", target: "dental"}},
	{data: {id: "Security"}},
	{data: {id: "benefits_Security", source: "benefits", target: "Security"}},
	{data: {id: "productivity"}},
	{data: {id: "benefits_productivity", source: "benefits", target: "productivity"}},
	{data: {id: "coverage"}},
	{data: {id: "benefits_coverage", source: "benefits", target: "coverage"}},
	{data: {id: "allies"}},
	{data: {id: "Japan"}},
	{data: {id: "allies_Japan", source: "allies", target: "Japan"}},
	{data: {id: "bodies"}},
	{data: {id: "World"}},
	{data: {id: "bodies_World", source: "bodies", target: "World"}},
	{data: {id: "International"}},
	{data: {id: "bodies_International", source: "bodies", target: "International"}},
	{data: {id: "Nations"}},
	{data: {id: "bodies_Nations", source: "bodies", target: "Nations"}},
	{data: {id: "Committee"}},
	{data: {id: "bodies_Committee", source: "bodies", target: "Committee"}},
	{data: {id: "Union"}},
	{data: {id: "bodies_Union", source: "bodies", target: "Union"}},
	{data: {id: "Bank"}},
	{data: {id: "bodies_Bank", source: "bodies", target: "Bank"}},
	{data: {id: "Congress"}},
	{data: {id: "bodies_Congress", source: "bodies", target: "Congress"}},
	{data: {id: "United"}},
	{data: {id: "bodies_United", source: "bodies", target: "United"}},
	{data: {id: "services"}},
	{data: {id: "mediation"}},
	{data: {id: "services_mediation", source: "services", target: "mediation"}},
	{data: {id: "marketing"}},
	{data: {id: "services_marketing", source: "services", target: "marketing"}},
	{data: {id: "health"}},
	{data: {id: "services_health", source: "services", target: "health"}},
	{data: {id: "removal"}},
	{data: {id: "services_removal", source: "services", target: "removal"}},
	{data: {id: "shipping"}},
	{data: {id: "services_shipping", source: "services", target: "shipping"}},
	{data: {id: "consultation"}},
	{data: {id: "services_consultation", source: "services", target: "consultation"}},
	{data: {id: "Internet"}},
	{data: {id: "services_Internet", source: "services", target: "Internet"}},
	{data: {id: "personnel"}},
	{data: {id: "services_personnel", source: "services", target: "personnel"}},
	{data: {id: "care"}},
	{data: {id: "services_care", source: "services", target: "care"}},
	{data: {id: "response"}},
	{data: {id: "services_response", source: "services", target: "response"}},
	{data: {id: "facilities"}},
	{data: {id: "pool"}},
	{data: {id: "facilities_pool", source: "facilities", target: "pool"}},
	{data: {id: "shop"}},
	{data: {id: "facilities_shop", source: "facilities", target: "shop"}},
	{data: {id: "library"}},
	{data: {id: "facilities_library", source: "facilities", target: "library"}},
	{data: {id: "centers"}},
	{data: {id: "Center"}},
	{data: {id: "centers_Center", source: "centers", target: "Center"}},
	{data: {id: "facilities_centers", source: "facilities", target: "centers"}},
	{data: {id: "Hospital"}},
	{data: {id: "facilities_Hospital", source: "facilities", target: "Hospital"}},
	{data: {id: "laboratory"}},
	{data: {id: "facilities_laboratory", source: "facilities", target: "laboratory"}},
	{data: {id: "store"}},
	{data: {id: "facilities_store", source: "facilities", target: "store"}},
	{data: {id: "center"}},
	{data: {id: "facilities_center", source: "facilities", target: "center"}},
	{data: {id: "station"}},
	{data: {id: "facilities_station", source: "facilities", target: "station"}},
	{data: {id: "stations"}},
	{data: {id: "facilities_stations", source: "facilities", target: "stations"}},
	{data: {id: "services_facilities", source: "services", target: "facilities"}},
	{data: {id: "support"}},
	{data: {id: "services_support", source: "services", target: "support"}},
	{data: {id: "customer"}},
	{data: {id: "services_customer", source: "services", target: "customer"}},
	{data: {id: "software"}},
	{data: {id: "Windows"}},
	{data: {id: "software_Windows", source: "software", target: "Windows"}},
	{data: {id: "spreadsheet"}},
	{data: {id: "software_spreadsheet", source: "software", target: "spreadsheet"}},
	{data: {id: "services_software", source: "services", target: "software"}},
	{data: {id: "planning"}},
	{data: {id: "services_planning", source: "services", target: "planning"}},
	{data: {id: "exchange"}},
	{data: {id: "services_exchange", source: "services", target: "exchange"}},
	{data: {id: "distribution"}},
	{data: {id: "services_distribution", source: "services", target: "distribution"}},
	{data: {id: "banking"}},
	{data: {id: "services_banking", source: "services", target: "banking"}},
	{data: {id: "family"}},
	{data: {id: "services_family", source: "services", target: "family"}},
	{data: {id: "dialysis"}},
	{data: {id: "services_dialysis", source: "services", target: "dialysis"}},
	{data: {id: "management"}},
	{data: {id: "services_management", source: "services", target: "management"}},
	{data: {id: "child"}},
	{data: {id: "services_child", source: "services", target: "child"}},
	{data: {id: "placement"}},
	{data: {id: "services_placement", source: "services", target: "placement"}},
	{data: {id: "monitoring"}},
	{data: {id: "services_monitoring", source: "services", target: "monitoring"}},
	{data: {id: "access"}},
	{data: {id: "services_access", source: "services", target: "access"}},
	{data: {id: "voice"}},
	{data: {id: "services_voice", source: "services", target: "voice"}},
	{data: {id: "translation"}},
	{data: {id: "services_translation", source: "services", target: "translation"}},
	{data: {id: "trust"}},
	{data: {id: "services_trust", source: "services", target: "trust"}},
	{data: {id: "physician"}},
	{data: {id: "services_physician", source: "services", target: "physician"}},
	{data: {id: "storage"}},
	{data: {id: "services_storage", source: "services", target: "storage"}},
	{data: {id: "data"}},
	{data: {id: "names"}},
	{data: {id: "data_names", source: "data", target: "names"}},
	{data: {id: "use"}},
	{data: {id: "data_use", source: "data", target: "use"}},
	{data: {id: "GDP"}},
	{data: {id: "data_GDP", source: "data", target: "GDP"}},
	{data: {id: "temperature"}},
	{data: {id: "data_temperature", source: "data", target: "temperature"}},
	{data: {id: "rates"}},
	{data: {id: "data_rates", source: "data", target: "rates"}},
	{data: {id: "services_data", source: "services", target: "data"}},
	{data: {id: "police"}},
	{data: {id: "services_police", source: "services", target: "police"}},
	{data: {id: "housing"}},
	{data: {id: "services_housing", source: "services", target: "housing"}},
	{data: {id: "treatment"}},
	{data: {id: "services_treatment", source: "services", target: "treatment"}},
	{data: {id: "processing"}},
	{data: {id: "services_processing", source: "services", target: "processing"}},
	{data: {id: "telephone"}},
	{data: {id: "services_telephone", source: "services", target: "telephone"}},
	{data: {id: "training"}},
	{data: {id: "services_training", source: "services", target: "training"}},
	{data: {id: "control"}},
	{data: {id: "services_control", source: "services", target: "control"}},
	{data: {id: "funds"}},
	{data: {id: "Fund"}},
	{data: {id: "funds_Fund", source: "funds", target: "Fund"}},
	{data: {id: "services_funds", source: "services", target: "funds"}},
	{data: {id: "accommodation"}},
	{data: {id: "services_accommodation", source: "services", target: "accommodation"}},
	{data: {id: "surgery"}},
	{data: {id: "services_surgery", source: "services", target: "surgery"}},
	{data: {id: "insurance"}},
	{data: {id: "services_insurance", source: "services", target: "insurance"}},
	{data: {id: "prenatal"}},
	{data: {id: "services_prenatal", source: "services", target: "prenatal"}},
	{data: {id: "therapy"}},
	{data: {id: "services_therapy", source: "services", target: "therapy"}},
	{data: {id: "emergency"}},
	{data: {id: "services_emergency", source: "services", target: "emergency"}},
	{data: {id: "guidance"}},
	{data: {id: "services_guidance", source: "services", target: "guidance"}},
	{data: {id: "e-mail"}},
	{data: {id: "services_e-mail", source: "services", target: "e-mail"}},
	{data: {id: "repair"}},
	{data: {id: "services_repair", source: "services", target: "repair"}},
	{data: {id: "assistance"}},
	{data: {id: "services_assistance", source: "services", target: "assistance"}},
	{data: {id: "transportation"}},
	{data: {id: "services_transportation", source: "services", target: "transportation"}},
	{data: {id: "home"}},
	{data: {id: "services_home", source: "services", target: "home"}},
	{data: {id: "development"}},
	{data: {id: "services_development", source: "services", target: "development"}},
	{data: {id: "bodies_services", source: "bodies", target: "services"}},
	{data: {id: "Association"}},
	{data: {id: "bodies_Association", source: "bodies", target: "Association"}},
	{data: {id: "Organization"}},
	{data: {id: "bodies_Organization", source: "bodies", target: "Organization"}},
	{data: {id: "Council"}},
	{data: {id: "bodies_Council", source: "bodies", target: "Council"}},
	{data: {id: "effects"}},
	{data: {id: "gain"}},
	{data: {id: "effects_gain", source: "effects", target: "gain"}},
	{data: {id: "diarrhea"}},
	{data: {id: "effects_diarrhea", source: "effects", target: "diarrhea"}},
	{data: {id: "disruption"}},
	{data: {id: "effects_disruption", source: "effects", target: "disruption"}},
	{data: {id: "constipation"}},
	{data: {id: "effects_constipation", source: "effects", target: "constipation"}},
	{data: {id: "radiation"}},
	{data: {id: "effects_radiation", source: "effects", target: "radiation"}},
	{data: {id: "headache"}},
	{data: {id: "effects_headache", source: "effects", target: "headache"}},
	{data: {id: "problems"}},
	{data: {id: "system"}},
	{data: {id: "problems_system", source: "problems", target: "system"}},
	{data: {id: "unemployment"}},
	{data: {id: "problems_unemployment", source: "problems", target: "unemployment"}},
	{data: {id: "drug"}},
	{data: {id: "problems_drug", source: "problems", target: "drug"}},
	{data: {id: "pressure"}},
	{data: {id: "problems_pressure", source: "problems", target: "pressure"}},
	{data: {id: "environment"}},
	{data: {id: "problems_environment", source: "problems", target: "environment"}},
	{data: {id: "pollution"}},
	{data: {id: "problems_pollution", source: "problems", target: "pollution"}},
	{data: {id: "anxiety"}},
	{data: {id: "problems_anxiety", source: "problems", target: "anxiety"}},
	{data: {id: "delinquency"}},
	{data: {id: "problems_delinquency", source: "problems", target: "delinquency"}},
	{data: {id: "commitment"}},
	{data: {id: "problems_commitment", source: "problems", target: "commitment"}},
	{data: {id: "blood"}},
	{data: {id: "problems_blood", source: "problems", target: "blood"}},
	{data: {id: "rates"}},
	{data: {id: "problems_rates", source: "problems", target: "rates"}},
	{data: {id: "breath"}},
	{data: {id: "problems_breath", source: "problems", target: "breath"}},
	{data: {id: "alcoholism"}},
	{data: {id: "problems_alcoholism", source: "problems", target: "alcoholism"}},
	{data: {id: "pregnancy"}},
	{data: {id: "problems_pregnancy", source: "problems", target: "pregnancy"}},
	{data: {id: "rights"}},
	{data: {id: "speech"}},
	{data: {id: "rights_speech", source: "rights", target: "speech"}},
	{data: {id: "freedom"}},
	{data: {id: "rights_freedom", source: "rights", target: "freedom"}},
	{data: {id: "problems_rights", source: "problems", target: "rights"}},
	{data: {id: "crime"}},
	{data: {id: "problems_crime", source: "problems", target: "crime"}},
	{data: {id: "housing"}},
	{data: {id: "problems_housing", source: "problems", target: "housing"}},
	{data: {id: "change"}},
	{data: {id: "problems_change", source: "problems", target: "change"}},
	{data: {id: "breakdown"}},
	{data: {id: "problems_breakdown", source: "problems", target: "breakdown"}},
	{data: {id: "depression"}},
	{data: {id: "problems_depression", source: "problems", target: "depression"}},
	{data: {id: "shortness"}},
	{data: {id: "problems_shortness", source: "problems", target: "shortness"}},
	{data: {id: "cancer"}},
	{data: {id: "problems_cancer", source: "problems", target: "cancer"}},
	{data: {id: "illness"}},
	{data: {id: "problems_illness", source: "problems", target: "illness"}},
	{data: {id: "injustice"}},
	{data: {id: "problems_injustice", source: "problems", target: "injustice"}},
	{data: {id: "racism"}},
	{data: {id: "problems_racism", source: "problems", target: "racism"}},
	{data: {id: "disorders"}},
	{data: {id: "cord"}},
	{data: {id: "disorders_cord", source: "disorders", target: "cord"}},
	{data: {id: "atrophy"}},
	{data: {id: "disorders_atrophy", source: "disorders", target: "atrophy"}},
	{data: {id: "stroke"}},
	{data: {id: "disorders_stroke", source: "disorders", target: "stroke"}},
	{data: {id: "pain"}},
	{data: {id: "disorders_pain", source: "disorders", target: "pain"}},
	{data: {id: "syndrome"}},
	{data: {id: "disorders_syndrome", source: "disorders", target: "syndrome"}},
	{data: {id: "hypertension"}},
	{data: {id: "disorders_hypertension", source: "disorders", target: "hypertension"}},
	{data: {id: "schizophrenia"}},
	{data: {id: "disorders_schizophrenia", source: "disorders", target: "schizophrenia"}},
	{data: {id: "obesity"}},
	{data: {id: "disorders_obesity", source: "disorders", target: "obesity"}},
	{data: {id: "spinal"}},
	{data: {id: "disorders_spinal", source: "disorders", target: "spinal"}},
	{data: {id: "multiple"}},
	{data: {id: "disorders_multiple", source: "disorders", target: "multiple"}},
	{data: {id: "injury"}},
	{data: {id: "disorders_injury", source: "disorders", target: "injury"}},
	{data: {id: "autism"}},
	{data: {id: "disorders_autism", source: "disorders", target: "autism"}},
	{data: {id: "ALS"}},
	{data: {id: "disorders_ALS", source: "disorders", target: "ALS"}},
	{data: {id: "addiction"}},
	{data: {id: "disorders_addiction", source: "disorders", target: "addiction"}},
	{data: {id: "dementia"}},
	{data: {id: "disorders_dementia", source: "disorders", target: "dementia"}},
	{data: {id: "epilepsy"}},
	{data: {id: "disorders_epilepsy", source: "disorders", target: "epilepsy"}},
	{data: {id: "disease"}},
	{data: {id: "diabetes"}},
	{data: {id: "disease_diabetes", source: "disease", target: "diabetes"}},
	{data: {id: "asthma"}},
	{data: {id: "disease_asthma", source: "disease", target: "asthma"}},
	{data: {id: "heart"}},
	{data: {id: "disease_heart", source: "disease", target: "heart"}},
	{data: {id: "disorders_disease", source: "disorders", target: "disease"}},
	{data: {id: "sclerosis"}},
	{data: {id: "disorders_sclerosis", source: "disorders", target: "sclerosis"}},
	{data: {id: "problems_disorders", source: "problems", target: "disorders"}},
	{data: {id: "malaria"}},
	{data: {id: "problems_malaria", source: "problems", target: "malaria"}},
	{data: {id: "climate"}},
	{data: {id: "problems_climate", source: "problems", target: "climate"}},
	{data: {id: "failure"}},
	{data: {id: "problems_failure", source: "problems", target: "failure"}},
	{data: {id: "control"}},
	{data: {id: "problems_control", source: "problems", target: "control"}},
	{data: {id: "nausea"}},
	{data: {id: "problems_nausea", source: "problems", target: "nausea"}},
	{data: {id: "performance"}},
	{data: {id: "problems_performance", source: "problems", target: "performance"}},
	{data: {id: "substance"}},
	{data: {id: "problems_substance", source: "problems", target: "substance"}},
	{data: {id: "fear"}},
	{data: {id: "problems_fear", source: "problems", target: "fear"}},
	{data: {id: "AIDS"}},
	{data: {id: "problems_AIDS", source: "problems", target: "AIDS"}},
	{data: {id: "poverty"}},
	{data: {id: "problems_poverty", source: "problems", target: "poverty"}},
	{data: {id: "air"}},
	{data: {id: "problems_air", source: "problems", target: "air"}},
	{data: {id: "abuse"}},
	{data: {id: "problems_abuse", source: "problems", target: "abuse"}},
	{data: {id: "erosion"}},
	{data: {id: "problems_erosion", source: "problems", target: "erosion"}},
	{data: {id: "growth"}},
	{data: {id: "problems_growth", source: "problems", target: "growth"}},
	{data: {id: "damage"}},
	{data: {id: "problems_damage", source: "problems", target: "damage"}},
	{data: {id: "loss"}},
	{data: {id: "problems_loss", source: "problems", target: "loss"}},
	{data: {id: "attack"}},
	{data: {id: "problems_attack", source: "problems", target: "attack"}},
	{data: {id: "alcohol"}},
	{data: {id: "problems_alcohol", source: "problems", target: "alcohol"}},
	{data: {id: "development"}},
	{data: {id: "problems_development", source: "problems", target: "development"}},
	{data: {id: "violence"}},
	{data: {id: "problems_violence", source: "problems", target: "violence"}},
	{data: {id: "water"}},
	{data: {id: "problems_water", source: "problems", target: "water"}},
	{data: {id: "effects_problems", source: "effects", target: "problems"}},
	{data: {id: "chronic disease"}},
	{data: {id: "disease"}},
	{data: {id: "diabetes"}},
	{data: {id: "disease_diabetes", source: "disease", target: "diabetes"}},
	{data: {id: "asthma"}},
	{data: {id: "disease_asthma", source: "disease", target: "asthma"}},
	{data: {id: "heart"}},
	{data: {id: "disease_heart", source: "disease", target: "heart"}},
	{data: {id: "chronic disease_disease", source: "chronic disease", target: "disease"}},
	{data: {id: "research"}},
	{data: {id: "studies"}},
	{data: {id: "research_studies", source: "research", target: "studies"}},
	{data: {id: "matters"}},
	{data: {id: "welfare"}},
	{data: {id: "matters_welfare", source: "matters", target: "welfare"}},
	{data: {id: "selection"}},
	{data: {id: "matters_selection", source: "matters", target: "selection"}},
	{data: {id: "advice"}},
	{data: {id: "matters_advice", source: "matters", target: "advice"}},
	{data: {id: "privacy"}},
	{data: {id: "matters_privacy", source: "matters", target: "privacy"}},
	{data: {id: "costs"}},
	{data: {id: "services"}},
	{data: {id: "mediation"}},
	{data: {id: "services_mediation", source: "services", target: "mediation"}},
	{data: {id: "marketing"}},
	{data: {id: "services_marketing", source: "services", target: "marketing"}},
	{data: {id: "health"}},
	{data: {id: "services_health", source: "services", target: "health"}},
	{data: {id: "removal"}},
	{data: {id: "services_removal", source: "services", target: "removal"}},
	{data: {id: "shipping"}},
	{data: {id: "services_shipping", source: "services", target: "shipping"}},
	{data: {id: "consultation"}},
	{data: {id: "services_consultation", source: "services", target: "consultation"}},
	{data: {id: "Internet"}},
	{data: {id: "services_Internet", source: "services", target: "Internet"}},
	{data: {id: "personnel"}},
	{data: {id: "services_personnel", source: "services", target: "personnel"}},
	{data: {id: "care"}},
	{data: {id: "services_care", source: "services", target: "care"}},
	{data: {id: "response"}},
	{data: {id: "services_response", source: "services", target: "response"}},
	{data: {id: "facilities"}},
	{data: {id: "pool"}},
	{data: {id: "facilities_pool", source: "facilities", target: "pool"}},
	{data: {id: "shop"}},
	{data: {id: "facilities_shop", source: "facilities", target: "shop"}},
	{data: {id: "library"}},
	{data: {id: "facilities_library", source: "facilities", target: "library"}},
	{data: {id: "centers"}},
	{data: {id: "Center"}},
	{data: {id: "centers_Center", source: "centers", target: "Center"}},
	{data: {id: "facilities_centers", source: "facilities", target: "centers"}},
	{data: {id: "Hospital"}},
	{data: {id: "facilities_Hospital", source: "facilities", target: "Hospital"}},
	{data: {id: "laboratory"}},
	{data: {id: "facilities_laboratory", source: "facilities", target: "laboratory"}},
	{data: {id: "store"}},
	{data: {id: "facilities_store", source: "facilities", target: "store"}},
	{data: {id: "center"}},
	{data: {id: "facilities_center", source: "facilities", target: "center"}},
	{data: {id: "station"}},
	{data: {id: "facilities_station", source: "facilities", target: "station"}},
	{data: {id: "stations"}},
	{data: {id: "facilities_stations", source: "facilities", target: "stations"}},
	{data: {id: "services_facilities", source: "services", target: "facilities"}},
	{data: {id: "support"}},
	{data: {id: "services_support", source: "services", target: "support"}},
	{data: {id: "customer"}},
	{data: {id: "services_customer", source: "services", target: "customer"}},
	{data: {id: "software"}},
	{data: {id: "Windows"}},
	{data: {id: "software_Windows", source: "software", target: "Windows"}},
	{data: {id: "spreadsheet"}},
	{data: {id: "software_spreadsheet", source: "software", target: "spreadsheet"}},
	{data: {id: "services_software", source: "services", target: "software"}},
	{data: {id: "planning"}},
	{data: {id: "services_planning", source: "services", target: "planning"}},
	{data: {id: "exchange"}},
	{data: {id: "services_exchange", source: "services", target: "exchange"}},
	{data: {id: "distribution"}},
	{data: {id: "services_distribution", source: "services", target: "distribution"}},
	{data: {id: "banking"}},
	{data: {id: "services_banking", source: "services", target: "banking"}},
	{data: {id: "family"}},
	{data: {id: "services_family", source: "services", target: "family"}},
	{data: {id: "dialysis"}},
	{data: {id: "services_dialysis", source: "services", target: "dialysis"}},
	{data: {id: "management"}},
	{data: {id: "services_management", source: "services", target: "management"}},
	{data: {id: "child"}},
	{data: {id: "services_child", source: "services", target: "child"}},
	{data: {id: "placement"}},
	{data: {id: "services_placement", source: "services", target: "placement"}},
	{data: {id: "monitoring"}},
	{data: {id: "services_monitoring", source: "services", target: "monitoring"}},
	{data: {id: "access"}},
	{data: {id: "services_access", source: "services", target: "access"}},
	{data: {id: "voice"}},
	{data: {id: "services_voice", source: "services", target: "voice"}},
	{data: {id: "translation"}},
	{data: {id: "services_translation", source: "services", target: "translation"}},
	{data: {id: "trust"}},
	{data: {id: "services_trust", source: "services", target: "trust"}},
	{data: {id: "physician"}},
	{data: {id: "services_physician", source: "services", target: "physician"}},
	{data: {id: "storage"}},
	{data: {id: "services_storage", source: "services", target: "storage"}},
	{data: {id: "data"}},
	{data: {id: "names"}},
	{data: {id: "data_names", source: "data", target: "names"}},
	{data: {id: "use"}},
	{data: {id: "data_use", source: "data", target: "use"}},
	{data: {id: "GDP"}},
	{data: {id: "data_GDP", source: "data", target: "GDP"}},
	{data: {id: "temperature"}},
	{data: {id: "data_temperature", source: "data", target: "temperature"}},
	{data: {id: "rates"}},
	{data: {id: "data_rates", source: "data", target: "rates"}},
	{data: {id: "services_data", source: "services", target: "data"}},
	{data: {id: "police"}},
	{data: {id: "services_police", source: "services", target: "police"}},
	{data: {id: "housing"}},
	{data: {id: "services_housing", source: "services", target: "housing"}},
	{data: {id: "treatment"}},
	{data: {id: "services_treatment", source: "services", target: "treatment"}},
	{data: {id: "processing"}},
	{data: {id: "services_processing", source: "services", target: "processing"}},
	{data: {id: "telephone"}},
	{data: {id: "services_telephone", source: "services", target: "telephone"}},
	{data: {id: "training"}},
	{data: {id: "services_training", source: "services", target: "training"}},
	{data: {id: "control"}},
	{data: {id: "services_control", source: "services", target: "control"}},
	{data: {id: "funds"}},
	{data: {id: "Fund"}},
	{data: {id: "funds_Fund", source: "funds", target: "Fund"}},
	{data: {id: "services_funds", source: "services", target: "funds"}},
	{data: {id: "accommodation"}},
	{data: {id: "services_accommodation", source: "services", target: "accommodation"}},
	{data: {id: "surgery"}},
	{data: {id: "services_surgery", source: "services", target: "surgery"}},
	{data: {id: "insurance"}},
	{data: {id: "services_insurance", source: "services", target: "insurance"}},
	{data: {id: "prenatal"}},
	{data: {id: "services_prenatal", source: "services", target: "prenatal"}},
	{data: {id: "therapy"}},
	{data: {id: "services_therapy", source: "services", target: "therapy"}},
	{data: {id: "emergency"}},
	{data: {id: "services_emergency", source: "services", target: "emergency"}},
	{data: {id: "guidance"}},
	{data: {id: "services_guidance", source: "services", target: "guidance"}},
	{data: {id: "e-mail"}},
	{data: {id: "services_e-mail", source: "services", target: "e-mail"}},
	{data: {id: "repair"}},
	{data: {id: "services_repair", source: "services", target: "repair"}},
	{data: {id: "assistance"}},
	{data: {id: "services_assistance", source: "services", target: "assistance"}},
	{data: {id: "transportation"}},
	{data: {id: "services_transportation", source: "services", target: "transportation"}},
	{data: {id: "home"}},
	{data: {id: "services_home", source: "services", target: "home"}},
	{data: {id: "development"}},
	{data: {id: "services_development", source: "services", target: "development"}},
	{data: {id: "costs_services", source: "costs", target: "services"}},
	{data: {id: "depreciation"}},
	{data: {id: "costs_depreciation", source: "costs", target: "depreciation"}},
	{data: {id: "interest"}},
	{data: {id: "costs_interest", source: "costs", target: "interest"}},
	{data: {id: "overhead"}},
	{data: {id: "costs_overhead", source: "costs", target: "overhead"}},
	{data: {id: "cost"}},
	{data: {id: "costs_cost", source: "costs", target: "cost"}},
	{data: {id: "matters_costs", source: "matters", target: "costs"}},
	{data: {id: "enforcement"}},
	{data: {id: "matters_enforcement", source: "matters", target: "enforcement"}},
	{data: {id: "finance"}},
	{data: {id: "matters_finance", source: "matters", target: "finance"}},
	{data: {id: "protection"}},
	{data: {id: "matters_protection", source: "matters", target: "protection"}},
	{data: {id: "rights"}},
	{data: {id: "speech"}},
	{data: {id: "rights_speech", source: "rights", target: "speech"}},
	{data: {id: "freedom"}},
	{data: {id: "rights_freedom", source: "rights", target: "freedom"}},
	{data: {id: "matters_rights", source: "matters", target: "rights"}},
	{data: {id: "age"}},
	{data: {id: "matters_age", source: "matters", target: "age"}},
	{data: {id: "projects"}},
	{data: {id: "studies"}},
	{data: {id: "projects_studies", source: "projects", target: "studies"}},
	{data: {id: "University"}},
	{data: {id: "projects_University", source: "projects", target: "University"}},
	{data: {id: "facilities"}},
	{data: {id: "pool"}},
	{data: {id: "facilities_pool", source: "facilities", target: "pool"}},
	{data: {id: "shop"}},
	{data: {id: "facilities_shop", source: "facilities", target: "shop"}},
	{data: {id: "library"}},
	{data: {id: "facilities_library", source: "facilities", target: "library"}},
	{data: {id: "centers"}},
	{data: {id: "Center"}},
	{data: {id: "centers_Center", source: "centers", target: "Center"}},
	{data: {id: "facilities_centers", source: "facilities", target: "centers"}},
	{data: {id: "Hospital"}},
	{data: {id: "facilities_Hospital", source: "facilities", target: "Hospital"}},
	{data: {id: "laboratory"}},
	{data: {id: "facilities_laboratory", source: "facilities", target: "laboratory"}},
	{data: {id: "store"}},
	{data: {id: "facilities_store", source: "facilities", target: "store"}},
	{data: {id: "center"}},
	{data: {id: "facilities_center", source: "facilities", target: "center"}},
	{data: {id: "station"}},
	{data: {id: "facilities_station", source: "facilities", target: "station"}},
	{data: {id: "stations"}},
	{data: {id: "facilities_stations", source: "facilities", target: "stations"}},
	{data: {id: "projects_facilities", source: "projects", target: "facilities"}},
	{data: {id: "matters_projects", source: "matters", target: "projects"}},
	{data: {id: "marriage"}},
	{data: {id: "matters_marriage", source: "matters", target: "marriage"}},
	{data: {id: "copyright"}},
	{data: {id: "matters_copyright", source: "matters", target: "copyright"}},
	{data: {id: "procedure"}},
	{data: {id: "matters_procedure", source: "matters", target: "procedure"}},
	{data: {id: "divorce"}},
	{data: {id: "matters_divorce", source: "matters", target: "divorce"}},
	{data: {id: "disabilities"}},
	{data: {id: "palsy"}},
	{data: {id: "disabilities_palsy", source: "disabilities", target: "palsy"}},
	{data: {id: "autism"}},
	{data: {id: "disabilities_autism", source: "disabilities", target: "autism"}},
	{data: {id: "retardation"}},
	{data: {id: "disabilities_retardation", source: "disabilities", target: "retardation"}},
	{data: {id: "mental"}},
	{data: {id: "disabilities_mental", source: "disabilities", target: "mental"}},
	{data: {id: "infrastructure"}},
	{data: {id: "network"}},
	{data: {id: "infrastructure_network", source: "infrastructure", target: "network"}},
	{data: {id: "transportation"}},
	{data: {id: "infrastructure_transportation", source: "infrastructure", target: "transportation"}},
	{data: {id: "communications"}},
	{data: {id: "infrastructure_communications", source: "infrastructure", target: "communications"}},
	{data: {id: "roads"}},
	{data: {id: "infrastructure_roads", source: "infrastructure", target: "roads"}},
	{data: {id: "housing"}},
	{data: {id: "infrastructure_housing", source: "infrastructure", target: "housing"}},
	{data: {id: "facilities"}},
	{data: {id: "pool"}},
	{data: {id: "facilities_pool", source: "facilities", target: "pool"}},
	{data: {id: "shop"}},
	{data: {id: "facilities_shop", source: "facilities", target: "shop"}},
	{data: {id: "library"}},
	{data: {id: "facilities_library", source: "facilities", target: "library"}},
	{data: {id: "centers"}},
	{data: {id: "Center"}},
	{data: {id: "centers_Center", source: "centers", target: "Center"}},
	{data: {id: "facilities_centers", source: "facilities", target: "centers"}},
	{data: {id: "Hospital"}},
	{data: {id: "facilities_Hospital", source: "facilities", target: "Hospital"}},
	{data: {id: "laboratory"}},
	{data: {id: "facilities_laboratory", source: "facilities", target: "laboratory"}},
	{data: {id: "store"}},
	{data: {id: "facilities_store", source: "facilities", target: "store"}},
	{data: {id: "center"}},
	{data: {id: "facilities_center", source: "facilities", target: "center"}},
	{data: {id: "station"}},
	{data: {id: "facilities_station", source: "facilities", target: "station"}},
	{data: {id: "stations"}},
	{data: {id: "facilities_stations", source: "facilities", target: "stations"}},
	{data: {id: "infrastructure_facilities", source: "infrastructure", target: "facilities"}},
	{data: {id: "systems"}},
	{data: {id: "aircraft"}},
	{data: {id: "systems_aircraft", source: "systems", target: "aircraft"}},
	{data: {id: "security"}},
	{data: {id: "systems_security", source: "systems", target: "security"}},
	{data: {id: "infrastructure_systems", source: "infrastructure", target: "systems"}},
	{data: {id: "documentation"}},
	{data: {id: "data"}},
	{data: {id: "names"}},
	{data: {id: "data_names", source: "data", target: "names"}},
	{data: {id: "use"}},
	{data: {id: "data_use", source: "data", target: "use"}},
	{data: {id: "GDP"}},
	{data: {id: "data_GDP", source: "data", target: "GDP"}},
	{data: {id: "temperature"}},
	{data: {id: "data_temperature", source: "data", target: "temperature"}},
	{data: {id: "rates"}},
	{data: {id: "data_rates", source: "data", target: "rates"}},
	{data: {id: "documentation_data", source: "documentation", target: "data"}},
	{data: {id: "institutes"}},
	{data: {id: "Institute"}},
	{data: {id: "institutes_Institute", source: "institutes", target: "Institute"}},
	{data: {id: "Center"}},
	{data: {id: "institutes_Center", source: "institutes", target: "Center"}},
	{data: {id: "abnormalities"}},
	{data: {id: "disease"}},
	{data: {id: "diabetes"}},
	{data: {id: "disease_diabetes", source: "disease", target: "diabetes"}},
	{data: {id: "asthma"}},
	{data: {id: "disease_asthma", source: "disease", target: "asthma"}},
	{data: {id: "heart"}},
	{data: {id: "disease_heart", source: "disease", target: "heart"}},
	{data: {id: "abnormalities_disease", source: "abnormalities", target: "disease"}},
	{data: {id: "emerging markets"}},
	{data: {id: "India"}},
	{data: {id: "emerging markets_India", source: "emerging markets", target: "India"}},
	{data: {id: "China"}},
	{data: {id: "emerging markets_China", source: "emerging markets", target: "China"}},
	{data: {id: "technology"}},
	{data: {id: "computer"}},
	{data: {id: "technology_computer", source: "technology", target: "computer"}},
	{data: {id: "systems"}},
	{data: {id: "aircraft"}},
	{data: {id: "systems_aircraft", source: "systems", target: "aircraft"}},
	{data: {id: "security"}},
	{data: {id: "systems_security", source: "systems", target: "security"}},
	{data: {id: "technology_systems", source: "technology", target: "systems"}},
	{data: {id: "organs"}},
	{data: {id: "lungs"}},
	{data: {id: "organs_lungs", source: "organs", target: "lungs"}},
	{data: {id: "liver"}},
	{data: {id: "organs_liver", source: "organs", target: "liver"}},
	{data: {id: "heart"}},
	{data: {id: "organs_heart", source: "organs", target: "heart"}},
	{data: {id: "kidney"}},
	{data: {id: "organs_kidney", source: "organs", target: "kidney"}},
	{data: {id: "lung"}},
	{data: {id: "organs_lung", source: "organs", target: "lung"}},
	{data: {id: "positions"}},
	{data: {id: "secretary"}},
	{data: {id: "positions_secretary", source: "positions", target: "secretary"}},
	{data: {id: "President"}},
	{data: {id: "positions_President", source: "positions", target: "President"}},
	{data: {id: "management"}},
	{data: {id: "positions_management", source: "positions", target: "management"}},
	{data: {id: "difficulties"}},
	{data: {id: "problems"}},
	{data: {id: "system"}},
	{data: {id: "problems_system", source: "problems", target: "system"}},
	{data: {id: "unemployment"}},
	{data: {id: "problems_unemployment", source: "problems", target: "unemployment"}},
	{data: {id: "drug"}},
	{data: {id: "problems_drug", source: "problems", target: "drug"}},
	{data: {id: "pressure"}},
	{data: {id: "problems_pressure", source: "problems", target: "pressure"}},
	{data: {id: "environment"}},
	{data: {id: "problems_environment", source: "problems", target: "environment"}},
	{data: {id: "pollution"}},
	{data: {id: "problems_pollution", source: "problems", target: "pollution"}},
	{data: {id: "anxiety"}},
	{data: {id: "problems_anxiety", source: "problems", target: "anxiety"}},
	{data: {id: "delinquency"}},
	{data: {id: "problems_delinquency", source: "problems", target: "delinquency"}},
	{data: {id: "commitment"}},
	{data: {id: "problems_commitment", source: "problems", target: "commitment"}},
	{data: {id: "blood"}},
	{data: {id: "problems_blood", source: "problems", target: "blood"}},
	{data: {id: "rates"}},
	{data: {id: "problems_rates", source: "problems", target: "rates"}},
	{data: {id: "breath"}},
	{data: {id: "problems_breath", source: "problems", target: "breath"}},
	{data: {id: "alcoholism"}},
	{data: {id: "problems_alcoholism", source: "problems", target: "alcoholism"}},
	{data: {id: "pregnancy"}},
	{data: {id: "problems_pregnancy", source: "problems", target: "pregnancy"}},
	{data: {id: "rights"}},
	{data: {id: "speech"}},
	{data: {id: "rights_speech", source: "rights", target: "speech"}},
	{data: {id: "freedom"}},
	{data: {id: "rights_freedom", source: "rights", target: "freedom"}},
	{data: {id: "problems_rights", source: "problems", target: "rights"}},
	{data: {id: "crime"}},
	{data: {id: "problems_crime", source: "problems", target: "crime"}},
	{data: {id: "housing"}},
	{data: {id: "problems_housing", source: "problems", target: "housing"}},
	{data: {id: "change"}},
	{data: {id: "problems_change", source: "problems", target: "change"}},
	{data: {id: "breakdown"}},
	{data: {id: "problems_breakdown", source: "problems", target: "breakdown"}},
	{data: {id: "depression"}},
	{data: {id: "problems_depression", source: "problems", target: "depression"}},
	{data: {id: "shortness"}},
	{data: {id: "problems_shortness", source: "problems", target: "shortness"}},
	{data: {id: "cancer"}},
	{data: {id: "problems_cancer", source: "problems", target: "cancer"}},
	{data: {id: "illness"}},
	{data: {id: "problems_illness", source: "problems", target: "illness"}},
	{data: {id: "injustice"}},
	{data: {id: "problems_injustice", source: "problems", target: "injustice"}},
	{data: {id: "racism"}},
	{data: {id: "problems_racism", source: "problems", target: "racism"}},
	{data: {id: "disorders"}},
	{data: {id: "cord"}},
	{data: {id: "disorders_cord", source: "disorders", target: "cord"}},
	{data: {id: "atrophy"}},
	{data: {id: "disorders_atrophy", source: "disorders", target: "atrophy"}},
	{data: {id: "stroke"}},
	{data: {id: "disorders_stroke", source: "disorders", target: "stroke"}},
	{data: {id: "pain"}},
	{data: {id: "disorders_pain", source: "disorders", target: "pain"}},
	{data: {id: "syndrome"}},
	{data: {id: "disorders_syndrome", source: "disorders", target: "syndrome"}},
	{data: {id: "hypertension"}},
	{data: {id: "disorders_hypertension", source: "disorders", target: "hypertension"}},
	{data: {id: "schizophrenia"}},
	{data: {id: "disorders_schizophrenia", source: "disorders", target: "schizophrenia"}},
	{data: {id: "obesity"}},
	{data: {id: "disorders_obesity", source: "disorders", target: "obesity"}},
	{data: {id: "spinal"}},
	{data: {id: "disorders_spinal", source: "disorders", target: "spinal"}},
	{data: {id: "multiple"}},
	{data: {id: "disorders_multiple", source: "disorders", target: "multiple"}},
	{data: {id: "injury"}},
	{data: {id: "disorders_injury", source: "disorders", target: "injury"}},
	{data: {id: "autism"}},
	{data: {id: "disorders_autism", source: "disorders", target: "autism"}},
	{data: {id: "ALS"}},
	{data: {id: "disorders_ALS", source: "disorders", target: "ALS"}},
	{data: {id: "addiction"}},
	{data: {id: "disorders_addiction", source: "disorders", target: "addiction"}},
	{data: {id: "dementia"}},
	{data: {id: "disorders_dementia", source: "disorders", target: "dementia"}},
	{data: {id: "epilepsy"}},
	{data: {id: "disorders_epilepsy", source: "disorders", target: "epilepsy"}},
	{data: {id: "disease"}},
	{data: {id: "diabetes"}},
	{data: {id: "disease_diabetes", source: "disease", target: "diabetes"}},
	{data: {id: "asthma"}},
	{data: {id: "disease_asthma", source: "disease", target: "asthma"}},
	{data: {id: "heart"}},
	{data: {id: "disease_heart", source: "disease", target: "heart"}},
	{data: {id: "disorders_disease", source: "disorders", target: "disease"}},
	{data: {id: "sclerosis"}},
	{data: {id: "disorders_sclerosis", source: "disorders", target: "sclerosis"}},
	{data: {id: "problems_disorders", source: "problems", target: "disorders"}},
	{data: {id: "malaria"}},
	{data: {id: "problems_malaria", source: "problems", target: "malaria"}},
	{data: {id: "climate"}},
	{data: {id: "problems_climate", source: "problems", target: "climate"}},
	{data: {id: "failure"}},
	{data: {id: "problems_failure", source: "problems", target: "failure"}},
	{data: {id: "control"}},
	{data: {id: "problems_control", source: "problems", target: "control"}},
	{data: {id: "nausea"}},
	{data: {id: "problems_nausea", source: "problems", target: "nausea"}},
	{data: {id: "performance"}},
	{data: {id: "problems_performance", source: "problems", target: "performance"}},
	{data: {id: "substance"}},
	{data: {id: "problems_substance", source: "problems", target: "substance"}},
	{data: {id: "fear"}},
	{data: {id: "problems_fear", source: "problems", target: "fear"}},
	{data: {id: "AIDS"}},
	{data: {id: "problems_AIDS", source: "problems", target: "AIDS"}},
	{data: {id: "poverty"}},
	{data: {id: "problems_poverty", source: "problems", target: "poverty"}},
	{data: {id: "air"}},
	{data: {id: "problems_air", source: "problems", target: "air"}},
	{data: {id: "abuse"}},
	{data: {id: "problems_abuse", source: "problems", target: "abuse"}},
	{data: {id: "erosion"}},
	{data: {id: "problems_erosion", source: "problems", target: "erosion"}},
	{data: {id: "growth"}},
	{data: {id: "problems_growth", source: "problems", target: "growth"}},
	{data: {id: "damage"}},
	{data: {id: "problems_damage", source: "problems", target: "damage"}},
	{data: {id: "loss"}},
	{data: {id: "problems_loss", source: "problems", target: "loss"}},
	{data: {id: "attack"}},
	{data: {id: "problems_attack", source: "problems", target: "attack"}},
	{data: {id: "alcohol"}},
	{data: {id: "problems_alcohol", source: "problems", target: "alcohol"}},
	{data: {id: "development"}},
	{data: {id: "problems_development", source: "problems", target: "development"}},
	{data: {id: "violence"}},
	{data: {id: "problems_violence", source: "problems", target: "violence"}},
	{data: {id: "water"}},
	{data: {id: "problems_water", source: "problems", target: "water"}},
	{data: {id: "difficulties_problems", source: "difficulties", target: "problems"}},
	{data: {id: "means"}},
	{data: {id: "telephone"}},
	{data: {id: "means_telephone", source: "means", target: "telephone"}},
	{data: {id: "television"}},
	{data: {id: "means_television", source: "means", target: "television"}},
	{data: {id: "communications"}},
	{data: {id: "means_communications", source: "means", target: "communications"}},
	{data: {id: "categories"}},
	{data: {id: "services"}},
	{data: {id: "mediation"}},
	{data: {id: "services_mediation", source: "services", target: "mediation"}},
	{data: {id: "marketing"}},
	{data: {id: "services_marketing", source: "services", target: "marketing"}},
	{data: {id: "health"}},
	{data: {id: "services_health", source: "services", target: "health"}},
	{data: {id: "removal"}},
	{data: {id: "services_removal", source: "services", target: "removal"}},
	{data: {id: "shipping"}},
	{data: {id: "services_shipping", source: "services", target: "shipping"}},
	{data: {id: "consultation"}},
	{data: {id: "services_consultation", source: "services", target: "consultation"}},
	{data: {id: "Internet"}},
	{data: {id: "services_Internet", source: "services", target: "Internet"}},
	{data: {id: "personnel"}},
	{data: {id: "services_personnel", source: "services", target: "personnel"}},
	{data: {id: "care"}},
	{data: {id: "services_care", source: "services", target: "care"}},
	{data: {id: "response"}},
	{data: {id: "services_response", source: "services", target: "response"}},
	{data: {id: "facilities"}},
	{data: {id: "pool"}},
	{data: {id: "facilities_pool", source: "facilities", target: "pool"}},
	{data: {id: "shop"}},
	{data: {id: "facilities_shop", source: "facilities", target: "shop"}},
	{data: {id: "library"}},
	{data: {id: "facilities_library", source: "facilities", target: "library"}},
	{data: {id: "centers"}},
	{data: {id: "Center"}},
	{data: {id: "centers_Center", source: "centers", target: "Center"}},
	{data: {id: "facilities_centers", source: "facilities", target: "centers"}},
	{data: {id: "Hospital"}},
	{data: {id: "facilities_Hospital", source: "facilities", target: "Hospital"}},
	{data: {id: "laboratory"}},
	{data: {id: "facilities_laboratory", source: "facilities", target: "laboratory"}},
	{data: {id: "store"}},
	{data: {id: "facilities_store", source: "facilities", target: "store"}},
	{data: {id: "center"}},
	{data: {id: "facilities_center", source: "facilities", target: "center"}},
	{data: {id: "station"}},
	{data: {id: "facilities_station", source: "facilities", target: "station"}},
	{data: {id: "stations"}},
	{data: {id: "facilities_stations", source: "facilities", target: "stations"}},
	{data: {id: "services_facilities", source: "services", target: "facilities"}},
	{data: {id: "support"}},
	{data: {id: "services_support", source: "services", target: "support"}},
	{data: {id: "customer"}},
	{data: {id: "services_customer", source: "services", target: "customer"}},
	{data: {id: "software"}},
	{data: {id: "Windows"}},
	{data: {id: "software_Windows", source: "software", target: "Windows"}},
	{data: {id: "spreadsheet"}},
	{data: {id: "software_spreadsheet", source: "software", target: "spreadsheet"}},
	{data: {id: "services_software", source: "services", target: "software"}},
	{data: {id: "planning"}},
	{data: {id: "services_planning", source: "services", target: "planning"}},
	{data: {id: "exchange"}},
	{data: {id: "services_exchange", source: "services", target: "exchange"}},
	{data: {id: "distribution"}},
	{data: {id: "services_distribution", source: "services", target: "distribution"}},
	{data: {id: "banking"}},
	{data: {id: "services_banking", source: "services", target: "banking"}},
	{data: {id: "family"}},
	{data: {id: "services_family", source: "services", target: "family"}},
	{data: {id: "dialysis"}},
	{data: {id: "services_dialysis", source: "services", target: "dialysis"}},
	{data: {id: "management"}},
	{data: {id: "services_management", source: "services", target: "management"}},
	{data: {id: "child"}},
	{data: {id: "services_child", source: "services", target: "child"}},
	{data: {id: "placement"}},
	{data: {id: "services_placement", source: "services", target: "placement"}},
	{data: {id: "monitoring"}},
	{data: {id: "services_monitoring", source: "services", target: "monitoring"}},
	{data: {id: "access"}},
	{data: {id: "services_access", source: "services", target: "access"}},
	{data: {id: "voice"}},
	{data: {id: "services_voice", source: "services", target: "voice"}},
	{data: {id: "translation"}},
	{data: {id: "services_translation", source: "services", target: "translation"}},
	{data: {id: "trust"}},
	{data: {id: "services_trust", source: "services", target: "trust"}},
	{data: {id: "physician"}},
	{data: {id: "services_physician", source: "services", target: "physician"}},
	{data: {id: "storage"}},
	{data: {id: "services_storage", source: "services", target: "storage"}},
	{data: {id: "data"}},
	{data: {id: "names"}},
	{data: {id: "data_names", source: "data", target: "names"}},
	{data: {id: "use"}},
	{data: {id: "data_use", source: "data", target: "use"}},
	{data: {id: "GDP"}},
	{data: {id: "data_GDP", source: "data", target: "GDP"}},
	{data: {id: "temperature"}},
	{data: {id: "data_temperature", source: "data", target: "temperature"}},
	{data: {id: "rates"}},
	{data: {id: "data_rates", source: "data", target: "rates"}},
	{data: {id: "services_data", source: "services", target: "data"}},
	{data: {id: "police"}},
	{data: {id: "services_police", source: "services", target: "police"}},
	{data: {id: "housing"}},
	{data: {id: "services_housing", source: "services", target: "housing"}},
	{data: {id: "treatment"}},
	{data: {id: "services_treatment", source: "services", target: "treatment"}},
	{data: {id: "processing"}},
	{data: {id: "services_processing", source: "services", target: "processing"}},
	{data: {id: "telephone"}},
	{data: {id: "services_telephone", source: "services", target: "telephone"}},
	{data: {id: "training"}},
	{data: {id: "services_training", source: "services", target: "training"}},
	{data: {id: "control"}},
	{data: {id: "services_control", source: "services", target: "control"}},
	{data: {id: "funds"}},
	{data: {id: "Fund"}},
	{data: {id: "funds_Fund", source: "funds", target: "Fund"}},
	{data: {id: "services_funds", source: "services", target: "funds"}},
	{data: {id: "accommodation"}},
	{data: {id: "services_accommodation", source: "services", target: "accommodation"}},
	{data: {id: "surgery"}},
	{data: {id: "services_surgery", source: "services", target: "surgery"}},
	{data: {id: "insurance"}},
	{data: {id: "services_insurance", source: "services", target: "insurance"}},
	{data: {id: "prenatal"}},
	{data: {id: "services_prenatal", source: "services", target: "prenatal"}},
	{data: {id: "therapy"}},
	{data: {id: "services_therapy", source: "services", target: "therapy"}},
	{data: {id: "emergency"}},
	{data: {id: "services_emergency", source: "services", target: "emergency"}},
	{data: {id: "guidance"}},
	{data: {id: "services_guidance", source: "services", target: "guidance"}},
	{data: {id: "e-mail"}},
	{data: {id: "services_e-mail", source: "services", target: "e-mail"}},
	{data: {id: "repair"}},
	{data: {id: "services_repair", source: "services", target: "repair"}},
	{data: {id: "assistance"}},
	{data: {id: "services_assistance", source: "services", target: "assistance"}},
	{data: {id: "transportation"}},
	{data: {id: "services_transportation", source: "services", target: "transportation"}},
	{data: {id: "home"}},
	{data: {id: "services_home", source: "services", target: "home"}},
	{data: {id: "development"}},
	{data: {id: "services_development", source: "services", target: "development"}},
	{data: {id: "categories_services", source: "categories", target: "services"}},
	{data: {id: "powers"}},
	{data: {id: "Iran"}},
	{data: {id: "powers_Iran", source: "powers", target: "Iran"}},
	{data: {id: "details"}},
	{data: {id: "numbers"}},
	{data: {id: "details_numbers", source: "details", target: "numbers"}},
	{data: {id: "age"}},
	{data: {id: "details_age", source: "details", target: "age"}},
	{data: {id: "values"}},
	{data: {id: "fairness"}},
	{data: {id: "values_fairness", source: "values", target: "fairness"}},
	{data: {id: "health"}},
	{data: {id: "values_health", source: "values", target: "health"}},
	{data: {id: "freedom"}},
	{data: {id: "values_freedom", source: "values", target: "freedom"}},
	{data: {id: "honesty"}},
	{data: {id: "values_honesty", source: "values", target: "honesty"}},
	{data: {id: "democracy"}},
	{data: {id: "values_democracy", source: "values", target: "democracy"}},
	{data: {id: "equipment"}},
	{data: {id: "systems"}},
	{data: {id: "aircraft"}},
	{data: {id: "systems_aircraft", source: "systems", target: "aircraft"}},
	{data: {id: "security"}},
	{data: {id: "systems_security", source: "systems", target: "security"}},
	{data: {id: "equipment_systems", source: "equipment", target: "systems"}},
	{data: {id: "nations"}},
	{data: {id: "United"}},
	{data: {id: "nations_United", source: "nations", target: "United"}},
	{data: {id: "Vietnam"}},
	{data: {id: "nations_Vietnam", source: "nations", target: "Vietnam"}},
	{data: {id: "China"}},
	{data: {id: "nations_China", source: "nations", target: "China"}},
	{data: {id: "India"}},
	{data: {id: "nations_India", source: "nations", target: "India"}},
	{data: {id: "States"}},
	{data: {id: "nations_States", source: "nations", target: "States"}},
	{data: {id: "Kingdom"}},
	{data: {id: "nations_Kingdom", source: "nations", target: "Kingdom"}},
	{data: {id: "France"}},
	{data: {id: "nations_France", source: "nations", target: "France"}},
	{data: {id: "Union"}},
	{data: {id: "nations_Union", source: "nations", target: "Union"}},
	{data: {id: "England"}},
	{data: {id: "nations_England", source: "nations", target: "England"}},
	{data: {id: "Peru"}},
	{data: {id: "nations_Peru", source: "nations", target: "Peru"}},
	{data: {id: "Iran"}},
	{data: {id: "nations_Iran", source: "nations", target: "Iran"}},
	{data: {id: "Argentina"}},
	{data: {id: "nations_Argentina", source: "nations", target: "Argentina"}},
	{data: {id: "Brazil"}},
	{data: {id: "nations_Brazil", source: "nations", target: "Brazil"}},
	{data: {id: "Japan"}},
	{data: {id: "nations_Japan", source: "nations", target: "Japan"}},
	{data: {id: "Cuba"}},
	{data: {id: "nations_Cuba", source: "nations", target: "Cuba"}},
	{data: {id: "Mexico"}},
	{data: {id: "nations_Mexico", source: "nations", target: "Mexico"}},
	{data: {id: "Canada"}},
	{data: {id: "nations_Canada", source: "nations", target: "Canada"}},
	{data: {id: "Britain"}},
	{data: {id: "nations_Britain", source: "nations", target: "Britain"}},
	{data: {id: "needs"}},
	{data: {id: "costs"}},
	{data: {id: "services"}},
	{data: {id: "mediation"}},
	{data: {id: "services_mediation", source: "services", target: "mediation"}},
	{data: {id: "marketing"}},
	{data: {id: "services_marketing", source: "services", target: "marketing"}},
	{data: {id: "health"}},
	{data: {id: "services_health", source: "services", target: "health"}},
	{data: {id: "removal"}},
	{data: {id: "services_removal", source: "services", target: "removal"}},
	{data: {id: "shipping"}},
	{data: {id: "services_shipping", source: "services", target: "shipping"}},
	{data: {id: "consultation"}},
	{data: {id: "services_consultation", source: "services", target: "consultation"}},
	{data: {id: "Internet"}},
	{data: {id: "services_Internet", source: "services", target: "Internet"}},
	{data: {id: "personnel"}},
	{data: {id: "services_personnel", source: "services", target: "personnel"}},
	{data: {id: "care"}},
	{data: {id: "services_care", source: "services", target: "care"}},
	{data: {id: "response"}},
	{data: {id: "services_response", source: "services", target: "response"}},
	{data: {id: "facilities"}},
	{data: {id: "pool"}},
	{data: {id: "facilities_pool", source: "facilities", target: "pool"}},
	{data: {id: "shop"}},
	{data: {id: "facilities_shop", source: "facilities", target: "shop"}},
	{data: {id: "library"}},
	{data: {id: "facilities_library", source: "facilities", target: "library"}},
	{data: {id: "centers"}},
	{data: {id: "Center"}},
	{data: {id: "centers_Center", source: "centers", target: "Center"}},
	{data: {id: "facilities_centers", source: "facilities", target: "centers"}},
	{data: {id: "Hospital"}},
	{data: {id: "facilities_Hospital", source: "facilities", target: "Hospital"}},
	{data: {id: "laboratory"}},
	{data: {id: "facilities_laboratory", source: "facilities", target: "laboratory"}},
	{data: {id: "store"}},
	{data: {id: "facilities_store", source: "facilities", target: "store"}},
	{data: {id: "center"}},
	{data: {id: "facilities_center", source: "facilities", target: "center"}},
	{data: {id: "station"}},
	{data: {id: "facilities_station", source: "facilities", target: "station"}},
	{data: {id: "stations"}},
	{data: {id: "facilities_stations", source: "facilities", target: "stations"}},
	{data: {id: "services_facilities", source: "services", target: "facilities"}},
	{data: {id: "support"}},
	{data: {id: "services_support", source: "services", target: "support"}},
	{data: {id: "customer"}},
	{data: {id: "services_customer", source: "services", target: "customer"}},
	{data: {id: "software"}},
	{data: {id: "Windows"}},
	{data: {id: "software_Windows", source: "software", target: "Windows"}},
	{data: {id: "spreadsheet"}},
	{data: {id: "software_spreadsheet", source: "software", target: "spreadsheet"}},
	{data: {id: "services_software", source: "services", target: "software"}},
	{data: {id: "planning"}},
	{data: {id: "services_planning", source: "services", target: "planning"}},
	{data: {id: "exchange"}},
	{data: {id: "services_exchange", source: "services", target: "exchange"}},
	{data: {id: "distribution"}},
	{data: {id: "services_distribution", source: "services", target: "distribution"}},
	{data: {id: "banking"}},
	{data: {id: "services_banking", source: "services", target: "banking"}},
	{data: {id: "family"}},
	{data: {id: "services_family", source: "services", target: "family"}},
	{data: {id: "dialysis"}},
	{data: {id: "services_dialysis", source: "services", target: "dialysis"}},
	{data: {id: "management"}},
	{data: {id: "services_management", source: "services", target: "management"}},
	{data: {id: "child"}},
	{data: {id: "services_child", source: "services", target: "child"}},
	{data: {id: "placement"}},
	{data: {id: "services_placement", source: "services", target: "placement"}},
	{data: {id: "monitoring"}},
	{data: {id: "services_monitoring", source: "services", target: "monitoring"}},
	{data: {id: "access"}},
	{data: {id: "services_access", source: "services", target: "access"}},
	{data: {id: "voice"}},
	{data: {id: "services_voice", source: "services", target: "voice"}},
	{data: {id: "translation"}},
	{data: {id: "services_translation", source: "services", target: "translation"}},
	{data: {id: "trust"}},
	{data: {id: "services_trust", source: "services", target: "trust"}},
	{data: {id: "physician"}},
	{data: {id: "services_physician", source: "services", target: "physician"}},
	{data: {id: "storage"}},
	{data: {id: "services_storage", source: "services", target: "storage"}},
	{data: {id: "data"}},
	{data: {id: "names"}},
	{data: {id: "data_names", source: "data", target: "names"}},
	{data: {id: "use"}},
	{data: {id: "data_use", source: "data", target: "use"}},
	{data: {id: "GDP"}},
	{data: {id: "data_GDP", source: "data", target: "GDP"}},
	{data: {id: "temperature"}},
	{data: {id: "data_temperature", source: "data", target: "temperature"}},
	{data: {id: "rates"}},
	{data: {id: "data_rates", source: "data", target: "rates"}},
	{data: {id: "services_data", source: "services", target: "data"}},
	{data: {id: "police"}},
	{data: {id: "services_police", source: "services", target: "police"}},
	{data: {id: "housing"}},
	{data: {id: "services_housing", source: "services", target: "housing"}},
	{data: {id: "treatment"}},
	{data: {id: "services_treatment", source: "services", target: "treatment"}},
	{data: {id: "processing"}},
	{data: {id: "services_processing", source: "services", target: "processing"}},
	{data: {id: "telephone"}},
	{data: {id: "services_telephone", source: "services", target: "telephone"}},
	{data: {id: "training"}},
	{data: {id: "services_training", source: "services", target: "training"}},
	{data: {id: "control"}},
	{data: {id: "services_control", source: "services", target: "control"}},
	{data: {id: "funds"}},
	{data: {id: "Fund"}},
	{data: {id: "funds_Fund", source: "funds", target: "Fund"}},
	{data: {id: "services_funds", source: "services", target: "funds"}},
	{data: {id: "accommodation"}},
	{data: {id: "services_accommodation", source: "services", target: "accommodation"}},
	{data: {id: "surgery"}},
	{data: {id: "services_surgery", source: "services", target: "surgery"}},
	{data: {id: "insurance"}},
	{data: {id: "services_insurance", source: "services", target: "insurance"}},
	{data: {id: "prenatal"}},
	{data: {id: "services_prenatal", source: "services", target: "prenatal"}},
	{data: {id: "therapy"}},
	{data: {id: "services_therapy", source: "services", target: "therapy"}},
	{data: {id: "emergency"}},
	{data: {id: "services_emergency", source: "services", target: "emergency"}},
	{data: {id: "guidance"}},
	{data: {id: "services_guidance", source: "services", target: "guidance"}},
	{data: {id: "e-mail"}},
	{data: {id: "services_e-mail", source: "services", target: "e-mail"}},
	{data: {id: "repair"}},
	{data: {id: "services_repair", source: "services", target: "repair"}},
	{data: {id: "assistance"}},
	{data: {id: "services_assistance", source: "services", target: "assistance"}},
	{data: {id: "transportation"}},
	{data: {id: "services_transportation", source: "services", target: "transportation"}},
	{data: {id: "home"}},
	{data: {id: "services_home", source: "services", target: "home"}},
	{data: {id: "development"}},
	{data: {id: "services_development", source: "services", target: "development"}},
	{data: {id: "costs_services", source: "costs", target: "services"}},
	{data: {id: "depreciation"}},
	{data: {id: "costs_depreciation", source: "costs", target: "depreciation"}},
	{data: {id: "interest"}},
	{data: {id: "costs_interest", source: "costs", target: "interest"}},
	{data: {id: "overhead"}},
	{data: {id: "costs_overhead", source: "costs", target: "overhead"}},
	{data: {id: "cost"}},
	{data: {id: "costs_cost", source: "costs", target: "cost"}},
	{data: {id: "needs_costs", source: "needs", target: "costs"}},
	{data: {id: "maintenance"}},
	{data: {id: "needs_maintenance", source: "needs", target: "maintenance"}},
	{data: {id: "places"}},
	{data: {id: "stations"}},
	{data: {id: "places_stations", source: "places", target: "stations"}},
	{data: {id: "Mexico"}},
	{data: {id: "places_Mexico", source: "places", target: "Mexico"}},
	{data: {id: "Texas"}},
	{data: {id: "places_Texas", source: "places", target: "Texas"}},
	{data: {id: "University"}},
	{data: {id: "places_University", source: "places", target: "University"}},
	{data: {id: "Japan"}},
	{data: {id: "places_Japan", source: "places", target: "Japan"}},
	{data: {id: "California"}},
	{data: {id: "places_California", source: "places", target: "California"}},
	{data: {id: "Gulf"}},
	{data: {id: "places_Gulf", source: "places", target: "Gulf"}},
	{data: {id: "Paris"}},
	{data: {id: "places_Paris", source: "places", target: "Paris"}},
	{data: {id: "Chicago"}},
	{data: {id: "places_Chicago", source: "places", target: "Chicago"}},
	{data: {id: "China"}},
	{data: {id: "places_China", source: "places", target: "China"}},
	{data: {id: "centers"}},
	{data: {id: "Center"}},
	{data: {id: "centers_Center", source: "centers", target: "Center"}},
	{data: {id: "places_centers", source: "places", target: "centers"}},
	{data: {id: "Africa"}},
	{data: {id: "places_Africa", source: "places", target: "Africa"}},
	{data: {id: "Asia"}},
	{data: {id: "places_Asia", source: "places", target: "Asia"}},
	{data: {id: "Canada"}},
	{data: {id: "places_Canada", source: "places", target: "Canada"}},
	{data: {id: "Russia"}},
	{data: {id: "places_Russia", source: "places", target: "Russia"}},
	{data: {id: "India"}},
	{data: {id: "places_India", source: "places", target: "India"}},
	{data: {id: "devices"}},
	{data: {id: "memory"}},
	{data: {id: "devices_memory", source: "devices", target: "memory"}},
	{data: {id: "PC"}},
	{data: {id: "devices_PC", source: "devices", target: "PC"}},
	{data: {id: "tubes"}},
	{data: {id: "devices_tubes", source: "devices", target: "tubes"}},
	{data: {id: "systems"}},
	{data: {id: "aircraft"}},
	{data: {id: "systems_aircraft", source: "systems", target: "aircraft"}},
	{data: {id: "security"}},
	{data: {id: "systems_security", source: "systems", target: "security"}},
	{data: {id: "devices_systems", source: "devices", target: "systems"}},
	{data: {id: "sets"}},
	{data: {id: "devices_sets", source: "devices", target: "sets"}},
	{data: {id: "aids"}},
	{data: {id: "devices_aids", source: "devices", target: "aids"}}
];
